import type { ResumeChapterId } from './resume-chapters'

/** Generated by tools/build-resume-sculptures.mjs; each model embeds its articulated idle clip. */
export const resumeSculptureAssets = {
  "chegg": {
    "path": "resume-sculptures/chegg-82c7d6095892.glb",
    "title": "Cast interview microphone",
    "description": "A classic desk interview microphone is carried by a molded pewter yoke and tapered cast stem. Its elliptical weighted foot, seated clamp bearings and restrained metal grille share the site’s sculpture family. The acoustic head makes one small held adjustment on its real bearing axis.",
    "sha256": "82c7d6095892795b6ee6c5fc2c316f02c8b160b7d620f5b3f3de2aaf9ac1a109",
    "clips": [
      {
        "name": "idle",
        "duration": 9.199999809265137,
        "articulatedNodes": [
          "cast-microphone-acoustic-head"
        ]
      }
    ],
    "animationBounds": {
      "min": [
        -0.8055947521745379,
        -1.2500000000000002,
        -0.6684213742719265
      ],
      "max": [
        0.8055947521745379,
        1.27373966142318,
        0.6684213742719266
      ]
    }
  },
  "sapien": {
    "path": "resume-sculptures/sapien-529b71ff3296.glb",
    "title": "Audience portraits",
    "description": "Three distinct cast portraits rest on a continuous crescent. Brow, cheek, nose and mouth are sculpted into each head. Their neck joints turn inward, pause in attention, and return.",
    "sha256": "529b71ff3296a7da0bb7e9acf909950e5d61701ee5c90e40a81c34622f0d32bb",
    "clips": [
      {
        "name": "idle",
        "duration": 9.800000190734863,
        "articulatedNodes": [
          "portrait-neck-attention-0",
          "portrait-neck-attention-1",
          "portrait-neck-attention-2"
        ]
      }
    ],
    "animationBounds": {
      "min": [
        -1.2500000000000002,
        -0.9132999043634246,
        -0.6302066749674408
      ],
      "max": [
        1.2500000000000002,
        0.9147705983382675,
        0.6450282001354557
      ]
    }
  },
  "void": {
    "path": "resume-sculptures/void-10f8185598c2.glb",
    "title": "Bound evidence folio",
    "description": "A substantial tooled pewter folio binds curved pale sheets. A source record sits beside a ruled working leaf, linking the consulting practice’s research and financial planning. One real evidence leaf lifts gently at its bound spine, while the firm cover remains seated.",
    "sha256": "10f8185598c2727137e98445ca1ae9f2f9703f8f4b3445f41bdbbbb5773374c8",
    "clips": [
      {
        "name": "idle",
        "duration": 9.600000381469727,
        "articulatedNodes": [
          "Atlas-bound-evidence-leaf"
        ]
      }
    ],
    "animationBounds": {
      "min": [
        -1.2500000000000002,
        -1.0673638835895203,
        -0.8594675124310267
      ],
      "max": [
        1.25,
        1.0592528056931445,
        0.9742901883418427
      ]
    }
  },
  "internship-deadlines": {
    "path": "resume-sculptures/internship-deadlines-2b4bbe629813.glb",
    "title": "Pocket timekeeper",
    "description": "A pewter pocket timepiece with an engraved steel dial, fitted silver bezel, seated spade hands and a true suspension bow. The setting crown draws out, adjusts the minute hand by a small amount, pauses, and settles back.",
    "sha256": "2b4bbe629813ed927fcb609961494becbbfc9d2f5d5975e829ceed502c872edd",
    "clips": [
      {
        "name": "idle",
        "duration": 9.600000381469727,
        "articulatedNodes": [
          "fluted-setting-crown",
          "minute-hand-setting-spindle"
        ]
      }
    ],
    "animationBounds": {
      "min": [
        -0.999067096366368,
        -1.25,
        -0.652546041242442
      ],
      "max": [
        0.999067096366368,
        1.25,
        0.652546041242442
      ]
    }
  },
  "creative-trace": {
    "path": "resume-sculptures/creative-trace-446f03178c8c.glb",
    "title": "Editor’s loupe and contact folio",
    "description": "A shallow pewter print folio holds three engraved source crops of the same doorway and figure. A substantial handled metal loupe stays seated on the close crop and makes a quiet inspection sweep around its resting grip.",
    "sha256": "446f03178c8ca808c467280b61784192092a159d7bf4163e395ddea67783df6b",
    "clips": [
      {
        "name": "idle",
        "duration": 9.399999618530273,
        "articulatedNodes": [
          "seated-editor-loupe-inspection"
        ]
      }
    ],
    "animationBounds": {
      "min": [
        -1.25,
        -0.995972702513453,
        -0.7539063968015138
      ],
      "max": [
        1.2500000000000002,
        0.9959727025134528,
        0.7539063968015137
      ]
    }
  },
  "venture-labs": {
    "path": "resume-sculptures/venture-labs-e0226a39be7d.glb",
    "title": "Merchant’s balance",
    "description": "Two shallow metal pans hang from a cast balance beam above a fluted pedestal. The beam gently weighs both sides and settles at equilibrium; the suspended pans remain upright. An instrument for comparing the economics of a young business.",
    "sha256": "e0226a39be7d39dda4f4a770e5e56afb3e81e202b510d6d35d22fce1e7a54273",
    "clips": [
      {
        "name": "idle",
        "duration": 9.800000190734863,
        "articulatedNodes": [
          "balance-beam-knife-edge",
          "upright-suspended-pan--1",
          "upright-suspended-pan-1"
        ]
      }
    ],
    "animationBounds": {
      "min": [
        -1.2530550908091183,
        -0.9902946231896321,
        -0.6302495144231094
      ],
      "max": [
        1.2506251022970236,
        1.0489209007389966,
        0.6302495144231095
      ]
    }
  },
  "ai-venture": {
    "path": "resume-sculptures/ai-venture-1cc20a592b97.glb",
    "title": "Plate camera",
    "description": "A folding plate camera carries a deep five-leaf optical diaphragm, closed accordion bellows and a glass-plate holder. The lens focuses, the aperture opens for an exposure and the shutter release depresses. Its fitted metal standards and dark folded surfaces belong to the same engraved collection as the opening helmet.",
    "sha256": "1cc20a592b970c14a547f5ac3705baab6bbc2398518c8e7dcbc161be6e8a286c",
    "clips": [
      {
        "name": "idle",
        "duration": 10.399999618530273,
        "articulatedNodes": [
          "camera-aperture-leaf-0",
          "camera-aperture-leaf-1",
          "camera-aperture-leaf-2",
          "camera-aperture-leaf-3",
          "camera-aperture-leaf-4",
          "camera-focusing-wheel",
          "camera-shutter-release",
          "telescoping-camera-focus"
        ]
      }
    ],
    "animationBounds": {
      "min": [
        -1.2118609597851164,
        -1.1358485875413722,
        -1.25
      ],
      "max": [
        1.2118609597851164,
        1.1358485875413717,
        1.2500000000000002
      ]
    }
  }
} satisfies Record<ResumeChapterId, { path: string; title: string; description: string; sha256: string; clips: { name: string; duration: number; articulatedNodes: string[] }[]; animationBounds: { min: number[]; max: number[] } }>
