import type { ResumeChapterId } from './resume-chapters'

/** Generated by tools/build-resume-sculptures.mjs; each model embeds its articulated idle clip. */
export const resumeSculptureAssets = {
  "chegg": {
    "path": "resume-sculptures/chegg-be08298c1445.glb",
    "title": "Living folio",
    "description": "A substantial curved open book. One bound folio turns across the gutter while the two page blocks remain grounded.",
    "sha256": "be08298c14452e16c366f4ed8c92abd91aaeaedbf3a9b076ed8b71d2bcdb5543",
    "clips": [
      {
        "name": "idle",
        "duration": 7.199999809265137,
        "articulatedNodes": [
          "turning-folio"
        ]
      }
    ],
    "animationBounds": {
      "min": [
        -1.2499999999999998,
        -1.0474362394310779,
        -0.8588014568565255
      ],
      "max": [
        1.25,
        1.0096098624845031,
        1.2520983050605425
      ]
    }
  },
  "sapien": {
    "path": "resume-sculptures/sapien-e62335c66194.glb",
    "title": "Audience crescent",
    "description": "Three cast portrait forms share a composed crescent and gently turn toward one another, expressing attention and comparison.",
    "sha256": "e62335c661944d967cae345c16e47a7a8e3111b13522b18d497b401b5e9bac6e",
    "clips": [
      {
        "name": "idle",
        "duration": 8.399999618530273,
        "articulatedNodes": [
          "portrait-attention-0",
          "portrait-attention-1",
          "portrait-attention-2"
        ]
      }
    ],
    "animationBounds": {
      "min": [
        -1.2572439551079613,
        -0.8323719473304986,
        -0.8032976566251941
      ],
      "max": [
        1.2914380985846363,
        0.8352199536257878,
        0.7477817200658683
      ]
    }
  },
  "void": {
    "path": "resume-sculptures/void-ffb521eca315.glb",
    "title": "Structural knot",
    "description": "One continuous thick cast loop holds a smaller nested member. Its articulation reveals the structural relationship without breaking the knot silhouette.",
    "sha256": "ffb521eca31563ad09c32aa31b4fa2167e22a3c19954ca40628cf8a0ca85dabc",
    "clips": [
      {
        "name": "idle",
        "duration": 8.800000190734863,
        "articulatedNodes": [
          "nested-structural-member"
        ]
      }
    ],
    "animationBounds": {
      "min": [
        -1.2499999999999998,
        -1.1970088023393364,
        -0.8295796387414602
      ],
      "max": [
        1.2499999999999998,
        1.1970088023393362,
        0.8295796387414602
      ]
    }
  },
  "internship-deadlines": {
    "path": "resume-sculptures/internship-deadlines-51776f5b7763.glb",
    "title": "Perpetual calendar",
    "description": "A cast calendar instrument with a thick indexed day wheel, a grounded cradle, and a living day indicator.",
    "sha256": "51776f5b7763bbae28f9be0c4b7df5e50f9ed712fdf3b97eb4bd263894a945cb",
    "clips": [
      {
        "name": "idle",
        "duration": 9.600000381469727,
        "articulatedNodes": [
          "indexed-day-wheel",
          "moving-day-indicator"
        ]
      }
    ],
    "animationBounds": {
      "min": [
        -1.2122781748100149,
        -1.2499999999999998,
        -0.6143202400615544
      ],
      "max": [
        1.2122781748100149,
        1.3061584233421795,
        0.618718897739548
      ]
    }
  },
  "creative-trace": {
    "path": "resume-sculptures/creative-trace-5a2732e5e1db.glb",
    "title": "Living aperture",
    "description": "A substantial photographic lens with a recessed iris. Six fitted metal blades articulate together to open and close the optical pupil.",
    "sha256": "5a2732e5e1dbbf2ff8b31d55626567e533d6603c18796fb8c99efc168728d760",
    "clips": [
      {
        "name": "idle",
        "duration": 7.599999904632568,
        "articulatedNodes": [
          "iris-blade-pivot-0",
          "iris-blade-pivot-1",
          "iris-blade-pivot-2",
          "iris-blade-pivot-3",
          "iris-blade-pivot-4",
          "iris-blade-pivot-5"
        ]
      }
    ],
    "animationBounds": {
      "min": [
        -1.25,
        -1.2378725952269094,
        -0.843595897214369
      ],
      "max": [
        1.25,
        1.2378725952269094,
        0.8435958972143689
      ]
    }
  },
  "venture-labs": {
    "path": "resume-sculptures/venture-labs-491a5e86c9e2.glb",
    "title": "Cast balance",
    "description": "A sculpted commercial balance with a restrained moving beam. Weighted pans remain upright as the beam weighs alternatives.",
    "sha256": "491a5e86c9e2d6aefb8ff51ad9c8ea858a2a97193e339f1cdd52077d30b43f0a",
    "clips": [
      {
        "name": "idle",
        "duration": 8,
        "articulatedNodes": [
          "balance-beam",
          "left-weighted-pan",
          "right-weighted-pan"
        ]
      }
    ],
    "animationBounds": {
      "min": [
        -1.2500492621845423,
        -0.8422027477307096,
        -0.6167390387724992
      ],
      "max": [
        1.2500492621845423,
        0.9812564970480008,
        0.619549387697336
      ]
    }
  },
  "ai-venture": {
    "path": "resume-sculptures/ai-venture-bea7227d520e.glb",
    "title": "Folded light prism",
    "description": "Three substantial cast prism faces unfold around a central faceted light core. The volume changes from a closed prism to an open image-making instrument.",
    "sha256": "bea7227d520e003b93efcc405cb38335583013558e685c080e748daee14d6317",
    "clips": [
      {
        "name": "idle",
        "duration": 8.600000381469727,
        "articulatedNodes": [
          "folding-prism-face-0",
          "folding-prism-face-1",
          "folding-prism-face-2"
        ]
      }
    ],
    "animationBounds": {
      "min": [
        -0.8668242721803094,
        -1.251892289741191,
        -0.8977735142275771
      ],
      "max": [
        1.086708646363899,
        1.249999999871575,
        1.1656547672880693
      ]
    }
  }
} satisfies Record<ResumeChapterId, { path: string; title: string; description: string; sha256: string; clips: { name: string; duration: number; articulatedNodes: string[] }[]; animationBounds: { min: number[]; max: number[] } }>
