export interface RecruiterCompanyProfile {
  lines: [string, string, string, string]
}

// Two sentences in the original opening's four rows: an interest, then one fact.
// Personal claims follow the September-reviewed public profile and project records.
export const recruiterCompanyProfiles: Readonly<Record<string, RecruiterCompanyProfile>> = {
  "bcg": { lines: ["I’m drawn to BCG X’s", "AI products.", "I built Atlas for", "web research."] },
  "google": { lines: ["I care about Google’s", "search quality.", "I built a search tool for", "students."] },
  "microsoft": { lines: ["I’m drawn to Microsoft’s", "AI tools.", "At Chegg, I built an", "AI interviewer."] },
  "meta": { lines: ["I care about Meta’s", "content feeds.", "I analyzed posts with", "AI at Chegg."] },
  "amazon": { lines: ["I’m interested in Amazon’s", "return costs.", "I traced returned goods", "to resale."] },
  "adobe": { lines: ["I’m drawn to Adobe’s", "creative AI.", "I co-founded an AI", "image startup."] },
  "salesforce": { lines: ["I’m drawn to Salesforce’s", "sales AI.", "I wrote buyer use cases", "at Sapien."] },
  "servicenow": { lines: ["I’m drawn to ServiceNow’s", "workflows.", "I built Atlas for", "web audits."] },
  "intuit": { lines: ["I’m drawn to Intuit’s tools", "for small firms.", "At VOID, I developed", "operating plans."] },
  "atlassian": { lines: ["I’m drawn to Atlassian’s", "planning tools.", "I built a student planner", "for internships."] },
  "figma": { lines: ["I’m drawn to Figma’s", "design tools.", "I designed and built", "this portfolio."] },
  "notion": { lines: ["I care about how Notion", "organizes work.", "I built Atlas to link", "web findings."] },
  "databricks": { lines: ["I’m drawn to Databricks’", "AI data tools.", "I built a recruiting data", "pipeline."] },
  "datadog": { lines: ["I care how Datadog explains", "failures.", "I built a website audit", "tool in Python."] },
  "cloudflare": { lines: ["I follow Cloudflare’s", "crawler rules.", "I wrote about bot access", "and its limits."] },
  "duolingo": { lines: ["I’m drawn to Duolingo’s", "learning tools.", "At Chegg, I built an", "AI interviewer."] },
  "roblox": { lines: ["I’m drawn to Roblox’s", "creator tools.", "I built this site’s", "3D renderer."] },
  "harvey": { lines: ["I’m drawn to Harvey’s", "legal AI.", "I built Atlas with", "source links."] },
  "together-ai": { lines: ["I’m drawn to Together AI’s", "model tools.", "I co-founded an AI", "image startup."] },
  "lindy": { lines: ["I’m drawn to Lindy’s", "AI workflows.", "I built AI interviews", "with memory."] },
  "gumloop": { lines: ["I’m drawn to Gumloop’s", "data tools.", "I built a recruiting data", "pipeline."] },
  "rippling": { lines: ["I’m drawn to Rippling’s", "payroll tools.", "I led a payroll prototype", "on Solana."] },
  "stripe": { lines: ["I’m drawn to Stripe’s", "payment tools.", "I led a payroll prototype", "on Solana."] },
  "ramp": { lines: ["I’m drawn to Ramp’s", "spend controls.", "At VOID, I developed", "operating plans."] },
  "coinbase": { lines: ["I’m drawn to Coinbase’s", "client strategy.", "My entry was one of", "20 winners."] },
  "robinhood": { lines: ["I’m drawn to Robinhood’s", "market access.", "I researched index rules", "and fund flows."] },
  "base-power": { lines: ["I’m drawn to Base Power’s", "batteries.", "I studied hardware funding", "and power."] },
  "anduril": { lines: ["I’m curious how Anduril", "gets funded.", "I studied equipment finance", "for startups."] },
  "tesla": { lines: ["I’m drawn to Tesla’s", "energy storage.", "I researched hardware", "financing."] },
  "waymo": { lines: ["I’m curious who funds", "Waymo’s fleet.", "I traced its disclosed", "equity funding."] },
  "skydio": { lines: ["I’m drawn to Skydio’s", "drone business.", "I studied equipment finance", "for startups."] },
  "zipline": { lines: ["I’m drawn to Zipline’s", "delivery model.", "I studied return costs", "and logistics."] },
  "ge-vernova": { lines: ["I’m drawn to GE Vernova’s", "power work.", "I modeled AI compute from", "power supply."] },
  "texas-instruments": { lines: ["I’m drawn to TI’s", "fab investment.", "I researched magnet plant", "capacity."] },
  "amd": { lines: ["I’m curious about AMD’s", "power needs.", "I modeled compute from", "facility power."] },
  "vertiv": { lines: ["I’m drawn to Vertiv’s", "power systems.", "I modeled power needs for", "AI compute."] },
  "goldman-sachs": { lines: ["Goldman’s corporate finance", "interests me.", "I researched hardware", "financing."] },
  "jpmorgan": { lines: ["I’m drawn to JPMorgan’s", "business loans.", "I traced debt backed by", "airline loyalty."] },
  "capital-one": { lines: ["I’m drawn to Capital One’s", "credit products.", "I build financial models", "at Venture Labs."] },
  "blackrock": { lines: ["I follow BlackRock’s", "index funds.", "I studied index changes", "and fund flows."] },
  "blackstone": { lines: ["I’m drawn to Blackstone’s", "real assets.", "I traced housing ownership", "and its debt."] },
  "kkr": { lines: ["I follow KKR’s software", "investments.", "I reviewed 25 buyouts and", "their exit paths."] },
  "apollo": { lines: ["I’m drawn to Apollo’s", "credit work.", "I traced debt backed by", "airline loyalty."] },
  "jane-street": { lines: ["I’m drawn to Jane Street’s", "research.", "I solved its July 2026", "knight puzzle."] },
  "citadel-securities": { lines: ["Citadel Securities’ trading", "interests me.", "I studied index changes", "and fund flows."] },
  "d-e-shaw": { lines: ["I’m drawn to D. E. Shaw’s", "quant research.", "I built a solver and", "verified it."] },
  "bridgewater-associates": { lines: ["Bridgewater’s macro research", "interests me.", "I studied power constraints", "on AI compute."] },
  "vanguard": { lines: ["I’m drawn to Vanguard’s", "index funds.", "I studied index changes", "and fund flows."] },
  "mckinsey": { lines: ["I’m drawn to McKinsey’s", "strategy work.", "I build financial models", "at Venture Labs."] },
  "bain": { lines: ["I’m drawn to Bain’s", "customer work.", "I wrote pricing use cases", "at Sapien."] },
  "k1-investment-management": { lines: ["I follow K1’s software", "investments.", "I reviewed 25 buyouts and", "their exit paths."] },
  "hq-capital": { lines: ["I’m drawn to HQ Capital’s", "private markets.", "I reviewed 25 buyouts and", "their exit paths."] },
  "riveron": { lines: ["I’m drawn to Riveron’s", "finance work.", "At VOID, I developed", "operating plans."] },
  "pzena-investment-management": { lines: ["I’m drawn to Pzena’s", "value investing.", "I build financial models", "at Venture Labs."] },
  "massmutual": { lines: ["I follow MassMutual’s", "investments.", "I build financial models", "at Venture Labs."] },
  "plante-moran": { lines: ["I’m drawn to Plante Moran’s", "advisory work.", "At VOID, I developed plans", "for small firms."] },
  "northwood-space": { lines: ["I’m drawn to Northwood’s", "ground stations.", "I researched hardware", "startup funding."] },
  "dalio-family-office": { lines: ["I follow Dalio Family Office’s", "investments.", "I studied power constraints", "on AI compute."] },
  "muon-space": { lines: ["I’m drawn to Muon Space’s", "satellites.", "I researched hardware", "startup funding."] },
  "amca": { lines: ["Amca’s aircraft parts", "interest me.", "I researched magnet plant", "capacity."] },
  "k2-space": { lines: ["I’m drawn to K2 Space’s", "satellites.", "I researched hardware", "startup funding."] },
  "charles-river-associates": { lines: ["I’m drawn to CRA’s", "economics.", "I studied index changes", "and fund flows."] },
  "precision-aq-precision-medicine-group": { lines: ["I’m drawn to Precision AQ’s", "medical copy.", "At Sapien, I wrote content", "for buyers."] },
  "link-logistics": { lines: ["I’m drawn to Link Logistics’", "property work.", "I traced housing ownership", "and its debt."] },
  "related-companies": { lines: ["I’m drawn to Related’s", "property work.", "I traced housing ownership", "and its debt."] },
  "alvarez-and-marsal": { lines: ["I’m drawn to A&M’s", "recovery work.", "At VOID, I developed plans", "for small firms."] },
  "greystar": { lines: ["I’m drawn to Greystar’s", "housing work.", "I traced housing ownership", "and its debt."] },
  "berrydunn": { lines: ["I’m drawn to BerryDunn’s", "advisory work.", "At VOID, I developed plans", "for small firms."] },
  "bwxt": { lines: ["I’m drawn to BWXT’s", "nuclear work.", "I studied power constraints", "on AI compute."] },
  "keurig-dr-pepper": { lines: ["I care how buyers choose", "KDP’s drinks.", "I wrote pricing use cases", "at Sapien."] },
  "moet-hennessy-usa-lvmh": { lines: ["I care how buyers choose", "Moët Hennessy.", "At Sapien, I wrote content", "for buyers."] },
  "state-farm": { lines: ["I’m curious how State Farm", "prices risk.", "I build financial models", "at Venture Labs."] },
  "ghj": { lines: ["I’m drawn to GHJ’s", "advisory work.", "At VOID, I developed plans", "for small firms."] },
  "kyndryl": { lines: ["I’m drawn to Kyndryl’s", "IT systems.", "I built Atlas for", "web audits."] },
  "berkeley-research-group-brg": { lines: ["I’m drawn to BRG’s", "economics.", "I traced toll-road revenue", "and its debt."] },
  "js-held-ocean-tomo": { lines: ["I’m drawn to Ocean Tomo’s", "IP valuation.", "I build financial models", "at Venture Labs."] },
  "trumid": { lines: ["I’m drawn to Trumid’s", "bond markets.", "I studied index changes", "and fund flows."] },
  "parametric-morgan-stanley-investment-management": { lines: ["I follow Parametric’s", "portfolio rules.", "I studied index changes", "and fund flows."] },
  "impulse-space": { lines: ["I’m drawn to Impulse Space’s", "orbital work.", "I researched hardware", "startup funding."] },
  "bpm-llp": { lines: ["I’m drawn to BPM’s", "advisory work.", "At VOID, I developed plans", "for small firms."] },
}

export function recruiterCompanyProfile(slug: string, companyName: string): RecruiterCompanyProfile {
  if (Object.hasOwn(recruiterCompanyProfiles, slug)) return recruiterCompanyProfiles[slug]
  return {
    lines: [`Hello, ${companyName}.`, 'I’m Sulayman.', 'My work spans product', 'and research.'],
  }
}
