export type RecruiterWorkKey = 'internshipdeadlines' | 'atlas' | 'sapien' | 'markets' | 'payrollpro' | 'solver' | 'creative'

export interface RecruiterCompanyProfile {
  focus: string
  headline: [string, string]
  introduction: string
  priorities: [{ title: string; body: string }, { title: string; body: string }, { title: string; body: string }]
  work: [RecruiterWorkKey, RecruiterWorkKey, RecruiterWorkKey]
  reading: [string, string]
  experience: [string, string, string]
}

// Fit areas are editorial selections, not claims of an opening or affiliation.
// Personal evidence comes from the September-reviewed profile and public work.
const productExperience: RecruiterCompanyProfile['experience'] = ['Chegg, Inc.', 'InternshipDeadlines', 'Sapien']
const systemsExperience: RecruiterCompanyProfile['experience'] = ['VOID Agency', 'Chegg, Inc.', 'InternshipDeadlines']
const commercialExperience: RecruiterCompanyProfile['experience'] = ['Sapien', 'Jon Brumley Texas Venture Labs', 'VOID Agency']
const financeExperience: RecruiterCompanyProfile['experience'] = ['Jon Brumley Texas Venture Labs', 'VOID Agency', 'Chegg, Inc.']
const creativeExperience: RecruiterCompanyProfile['experience'] = ['CreativeTrace', 'AI Image Generation Startup', 'Chegg, Inc.']
const aiExperience: RecruiterCompanyProfile['experience'] = ['Chegg, Inc.', 'AI Image Generation Startup', 'Sapien']

const reading = {
  atlas: 'atlas-building-an-evidence-console',
  solver: 'jane-street-exact-search-solver-verification',
  tollCash: 'why-texas-toll-roads-stay-tolled',
  tollOwnership: 'who-owns-texas-toll-roads',
  buyouts: 'software-buyout-boom-2020-2022-exit-audit',
  magnets: 'us-rare-earth-magnet-manufacturing-capacity',
  power: 'the-ai-megawatt',
  homeServices: 'who-owns-austin-home-service-companies',
  index: 'what-happens-when-an-index-decides-a-company-matters',
  loyalty: 'how-airlines-borrow-against-loyalty-programs',
  returns: 'where-online-returns-actually-go',
  hardware: 'hidden-financing-hardware-startups',
  housing: 'west-campus-student-housing',
  waymo: 'waymo-hardware-financing',
  frontier: 'crawl-frontier-state-machine',
  traces: 'replayable-traces-ai-agent-evaluation',
  sqlite: 'sqlite-crawl-pipelines',
  releases: 'technical-seo-migration-release-gates',
  managers: 'the-first-ai-managers',
  viralbench: 'viralbench-codex-agent-harness',
  crawlers: 'ai-search-crawler-policy',
  infrastructure: 'technical-seo-public-data-infrastructure',
  graph: 'internal-links-directed-retrieval-graph',
  findings: 'audit-findings-derived-records',
} as const

const priority = (title: string, body: string) => ({ title, body })

export const recruiterCompanyProfiles: Readonly<Record<string, RecruiterCompanyProfile>> = {
  google: {
    focus: 'Search, discovery & AI product',
    headline: ['A useful answer.', 'A clear next step.'],
    introduction: 'For Google, I selected work on search relevance, source quality, and AI interactions. At Chegg and in InternshipDeadlines, I connect a user’s question to a useful, verifiable result.',
    priorities: [priority('Search intent', 'Translate an ambiguous question into ranked results and a useful action.'), priority('Source quality', 'Retain provenance as records are classified, normalized, and deduplicated.'), priority('AI interactions', 'Evaluate follow-ups, feedback, memory, and recovery through real workflows.')],
    work: ['internshipdeadlines', 'atlas', 'solver'],
    reading: [reading.graph, reading.crawlers],
    experience: productExperience,
  },
  microsoft: {
    focus: 'AI workflows & enterprise product',
    headline: ['Useful AI.', 'Inside real work.'],
    introduction: 'The Microsoft connection is practical AI: tools that help someone complete a task. My mock-interviewer work at Chegg and Atlas’s evidence workflow show how I move from an idea to a usable system.',
    priorities: [priority('Workflow design', 'Start with the task, the handoff, and the evidence of completion.'), priority('Reliable assistance', 'Account for interrupted conversations, missing information, and failure recovery.'), priority('Technical communication', 'Explain system behavior clearly enough for product and engineering decisions.')],
    work: ['internshipdeadlines', 'atlas', 'sapien'],
    reading: [reading.traces, reading.managers],
    experience: aiExperience,
  },
  meta: {
    focus: 'Consumer product, creative research & growth',
    headline: ['Understand the audience.', 'Build the experiment.'],
    introduction: 'For Meta, I would start with my work on public social data, creative hypotheses, and growth. Chegg, CreativeTrace, and Sapien connect audience research to the next product or messaging experiment.',
    priorities: [priority('Audience signals', 'Use public posts to develop questions and testable creative hypotheses.'), priority('Consumer research', 'Distinguish observed behavior from modeled responses and stated preferences.'), priority('Experiment design', 'Connect a change in messaging to a defined question and outcome.')],
    work: ['creative', 'sapien', 'internshipdeadlines'],
    reading: [reading.viralbench, reading.traces],
    experience: ['Chegg, Inc.', 'CreativeTrace', 'Sapien'],
  },
  amazon: {
    focus: 'Customer workflows & operating economics',
    headline: ['Follow the customer.', 'Then follow the cost.'],
    introduction: 'For Amazon, I selected product work alongside research on returns and operating economics. I enjoy tracing what happens after a customer action: the workflow, the cost, and the decision it creates.',
    priorities: [priority('Customer journeys', 'Map the steps between a search, a decision, and a completed task.'), priority('Operating economics', 'Make recovery value, cost, and cash-flow assumptions visible.'), priority('Information systems', 'Turn scattered source records into consistent, usable product data.')],
    work: ['internshipdeadlines', 'markets', 'atlas'],
    reading: [reading.returns, reading.hardware],
    experience: ['Chegg, Inc.', 'Jon Brumley Texas Venture Labs', 'InternshipDeadlines'],
  },
  adobe: {
    focus: 'Creative tools, AI & product positioning',
    headline: ['From creative intent', 'to a useful tool.'],
    introduction: 'For Adobe, the closest connection is my work across AI image generation, creative research, and interactive graphics. I care about how a tool fits the maker’s process and how its value is explained.',
    priorities: [priority('Creative workflows', 'Translate a creator’s goal into product requirements and interaction choices.'), priority('AI product judgment', 'Connect quality tradeoffs with pricing, positioning, and user needs.'), priority('Visual experimentation', 'Use light, texture, and motion to explore a concrete interaction.')],
    work: ['creative', 'sapien', 'internshipdeadlines'],
    reading: [reading.viralbench, reading.traces],
    experience: creativeExperience,
  },
  salesforce: {
    focus: 'Enterprise workflows & commercial AI',
    headline: ['A better workflow.', 'A clearer business case.'],
    introduction: 'For Salesforce, I selected systems and commercial work together. Building Atlas and developing Sapien’s buyer use cases taught me to connect what software does with the decision a customer needs to make.',
    priorities: [priority('Buyer use cases', 'Organize product explanations around a specific job and its evidence.'), priority('Workflow records', 'Keep actions, source facts, and derived findings connected.'), priority('AI evaluation', 'Separate a compelling demonstration from repeatable task performance.')],
    work: ['atlas', 'sapien', 'internshipdeadlines'],
    reading: [reading.managers, reading.traces],
    experience: ['VOID Agency', 'Sapien', 'Chegg, Inc.'],
  },
  servicenow: {
    focus: 'Workflow systems & automation',
    headline: ['Make the handoff', 'part of the product.'],
    introduction: 'The work I would bring to ServiceNow centers on workflow state: what has happened, what remains, and what evidence supports the next action. Atlas and InternshipDeadlines make those distinctions explicit.',
    priorities: [priority('State and ownership', 'Give records clear status, source history, and next actions.'), priority('Automation boundaries', 'Design for retries, missing information, and human review.'), priority('Usable reporting', 'Turn technical findings into decisions that a team can act on.')],
    work: ['atlas', 'internshipdeadlines', 'sapien'],
    reading: [reading.frontier, reading.findings],
    experience: systemsExperience,
  },
  intuit: {
    focus: 'Financial tools & small-business product',
    headline: ['Make the numbers', 'useful to someone.'],
    introduction: 'For Intuit, I selected work where finance meets a usable product. I study finance, run VOID, and build tools that make assumptions, comparisons, and the next decision easier to understand.',
    priorities: [priority('Financial clarity', 'Show the assumptions behind a comparison instead of only its answer.'), priority('Small-business context', 'Connect software choices with operating plans and commercial needs.'), priority('Product detail', 'Design records and workflows around what someone is trying to finish.')],
    work: ['internshipdeadlines', 'markets', 'payrollpro'],
    reading: [reading.homeServices, reading.loyalty],
    experience: ['VOID Agency', 'Jon Brumley Texas Venture Labs', 'InternshipDeadlines'],
  },
  atlassian: {
    focus: 'Team workflows & information design',
    headline: ['Work that stays', 'understandable.'],
    introduction: 'For Atlassian, I selected work on records, handoffs, and source history. My product decisions often come down to helping a team understand what a record means and what to do with it next.',
    priorities: [priority('Record design', 'Separate shared facts from personal plans and derived interpretations.'), priority('Team context', 'Retain the source and rationale when information changes hands.'), priority('Progress visibility', 'Make status and unresolved work explicit in the product.')],
    work: ['internshipdeadlines', 'atlas', 'sapien'],
    reading: [reading.findings, reading.frontier],
    experience: systemsExperience,
  },
  figma: {
    focus: 'Interaction design & creative product',
    headline: ['Think through it.', 'Make it tangible.'],
    introduction: 'For Figma, I would lead with the relationship between product thinking and making. I build interactive systems, study visual materials, and use prototypes to make a design decision concrete.',
    priorities: [priority('Interaction detail', 'Connect visual choices to orientation, feedback, and the next action.'), priority('Working prototypes', 'Use real behavior to inspect a design instead of relying on a mockup.'), priority('Creative research', 'Turn patterns and references into hypotheses a team can discuss.')],
    work: ['creative', 'internshipdeadlines', 'sapien'],
    reading: [reading.atlas, reading.viralbench],
    experience: ['CreativeTrace', 'InternshipDeadlines', 'Chegg, Inc.'],
  },
  notion: {
    focus: 'Knowledge products & connected workflows',
    headline: ['Give information', 'a useful structure.'],
    introduction: 'For Notion, I selected products that turn information into a workflow. InternshipDeadlines separates an employer’s record from a student’s plan; Atlas separates source captures from the findings built on them.',
    priorities: [priority('Information structure', 'Give facts, interpretations, and personal actions distinct places.'), priority('Connected workflows', 'Help someone move from finding information to using it.'), priority('AI assistance', 'Keep generated help connected to the underlying record and task.')],
    work: ['internshipdeadlines', 'atlas', 'sapien'],
    reading: [reading.findings, reading.graph],
    experience: productExperience,
  },
  databricks: {
    focus: 'Data pipelines & AI product',
    headline: ['Useful models start', 'with useful records.'],
    introduction: 'For Databricks, I selected work on data quality, classification, retrieval, and reproducibility. I build pipelines that preserve where a record came from and what changed before it reaches a user.',
    priorities: [priority('Data provenance', 'Keep normalization and deduplication connected to original sources.'), priority('Model applications', 'Use classification and retrieval inside a complete user workflow.'), priority('Reproducible evidence', 'Retain enough of a run to inspect its outputs and failures.')],
    work: ['atlas', 'internshipdeadlines', 'solver'],
    reading: [reading.sqlite, reading.traces],
    experience: systemsExperience,
  },
  datadog: {
    focus: 'System visibility & technical product',
    headline: ['Know what happened.', 'Know what it means.'],
    introduction: 'For Datadog, Atlas is the clearest starting point: captures, measurements, and findings kept together. I’m interested in turning system evidence into a useful explanation and an actionable decision.',
    priorities: [priority('Operational evidence', 'Keep observations tied to the run and source that produced them.'), priority('Failure visibility', 'Represent missing measurements and partial collection honestly.'), priority('Decision support', 'Explain which finding matters, why, and what should happen next.')],
    work: ['atlas', 'solver', 'internshipdeadlines'],
    reading: [reading.findings, reading.traces],
    experience: systemsExperience,
  },
  cloudflare: {
    focus: 'Web infrastructure & developer workflows',
    headline: ['Understand the web.', 'Build on evidence.'],
    introduction: 'For Cloudflare, I selected my crawler, web-systems, and AI-search work. Atlas and my technical writing explore how requests, source documents, rendered pages, and policy become distinct pieces of evidence.',
    priorities: [priority('Web behavior', 'Inspect the actual response and route rather than assume delivery.'), priority('Crawler systems', 'Model collection state, retries, and limits explicitly.'), priority('Developer explanations', 'Make technical contracts clear through examples and retained evidence.')],
    work: ['atlas', 'internshipdeadlines', 'solver'],
    reading: [reading.crawlers, reading.releases],
    experience: systemsExperience,
  },
  duolingo: {
    focus: 'Learning products & experimentation',
    headline: ['Make the next step', 'worth taking.'],
    introduction: 'For Duolingo, I selected my student-product and AI-feedback work. At Chegg, I develop tools through student research; in InternshipDeadlines, I connect information with a clear next step.',
    priorities: [priority('Student context', 'Start with the learner’s task, constraints, and unanswered question.'), priority('Adaptive feedback', 'Use follow-ups and conversation context to make assistance more useful.'), priority('Product experiments', 'Define what a change should help a person accomplish.')],
    work: ['internshipdeadlines', 'sapien', 'creative'],
    reading: [reading.traces, reading.viralbench],
    experience: productExperience,
  },
  roblox: {
    focus: 'Creator tools & interactive experiences',
    headline: ['Build the interaction.', 'Understand the creator.'],
    introduction: 'For Roblox, I selected my interactive graphics, creative research, and product work. I like tools that let someone make something and experiences whose behavior is as considered as their appearance.',
    priorities: [priority('Interactive systems', 'Use working graphics and controls to inspect an experience.'), priority('Creator needs', 'Connect creative intent with tool behavior and product requirements.'), priority('Audience research', 'Develop hypotheses from public creative and engagement patterns.')],
    work: ['creative', 'internshipdeadlines', 'sapien'],
    reading: [reading.viralbench, reading.managers],
    experience: creativeExperience,
  },
  harvey: {
    focus: 'Professional AI & evidence workflows',
    headline: ['Useful assistance.', 'Traceable reasoning.'],
    introduction: 'For Harvey, I selected work on AI assistance and the evidence behind an answer. Atlas keeps findings connected to sources, while my Chegg work covers conversation context, feedback, and recovery.',
    priorities: [priority('Evidence handling', 'Keep source material distinguishable from conclusions drawn from it.'), priority('Professional workflows', 'Design around a task’s review points and completion criteria.'), priority('AI evaluation', 'Inspect failures and repeatable behavior alongside successful examples.')],
    work: ['atlas', 'internshipdeadlines', 'solver'],
    reading: [reading.traces, reading.findings],
    experience: ['Chegg, Inc.', 'VOID Agency', 'Sapien'],
  },
  'together-ai': {
    focus: 'AI applications & evaluation',
    headline: ['A model becomes useful', 'inside a product.'],
    introduction: 'For Together AI, I selected the application side of my AI work: image generation, a conversational interviewer, and local classification and retrieval. I connect model choices with the user’s task and the product’s economics.',
    priorities: [priority('Application fit', 'Choose evaluation criteria from the workflow the model must support.'), priority('Quality tradeoffs', 'Connect output quality, product scope, and commercial positioning.'), priority('System evaluation', 'Retain failures and traces that make behavior inspectable.')],
    work: ['internshipdeadlines', 'solver', 'creative'],
    reading: [reading.traces, reading.power],
    experience: aiExperience,
  },
  lindy: {
    focus: 'AI assistants & workflow automation',
    headline: ['Finish the task.', 'Handle the interruption.'],
    introduction: 'For Lindy, I selected work on useful assistance rather than isolated prompts. My Chegg interviewer includes memory and recovery; Atlas makes workflow state and missing evidence visible.',
    priorities: [priority('Task completion', 'Define the useful end state before choosing the automated steps.'), priority('Conversation context', 'Support follow-ups without losing the user’s earlier intent.'), priority('Recovery paths', 'Make interruption and missing information part of the design.')],
    work: ['internshipdeadlines', 'atlas', 'sapien'],
    reading: [reading.managers, reading.traces],
    experience: ['Chegg, Inc.', 'VOID Agency', 'Sapien'],
  },
  gumloop: {
    focus: 'AI workflows & accessible automation',
    headline: ['Make the workflow', 'easy to reason about.'],
    introduction: 'For Gumloop, I selected systems that connect several small operations into a usable workflow. My work spans collecting data, classifying records, retaining sources, and presenting the result to someone who needs to act.',
    priorities: [priority('Workflow composition', 'Connect inputs, transformations, and outputs with a clear purpose.'), priority('Inspectable steps', 'Make intermediate records useful when a result needs review.'), priority('Practical automation', 'Build retries and partial results into the operating path.')],
    work: ['atlas', 'internshipdeadlines', 'sapien'],
    reading: [reading.frontier, reading.sqlite],
    experience: systemsExperience,
  },
  rippling: {
    focus: 'Business systems & financial workflows',
    headline: ['Shared records.', 'Clear operating rules.'],
    introduction: 'For Rippling, I selected work on connected records and business operations. PayrollPro is a hackathon prototype in payroll state and treasury approval; Atlas and InternshipDeadlines show the same care with source history and workflow boundaries.',
    priorities: [priority('System records', 'Keep identity and status consistent across related actions.'), priority('Approval workflows', 'Make permissions, state changes, and review points explicit.'), priority('Commercial context', 'Connect a product decision with the operating problem it solves.')],
    work: ['payrollpro', 'atlas', 'internshipdeadlines'],
    reading: [reading.frontier, reading.findings],
    experience: ['VOID Agency', 'Chegg, Inc.', 'Jon Brumley Texas Venture Labs'],
  },
  stripe: {
    focus: 'Financial infrastructure & developer product',
    headline: ['Precise systems.', 'Useful abstractions.'],
    introduction: 'For Stripe, I selected work at the boundary of financial logic and software. PayrollPro explores treasury and payroll state as a prototype; Atlas shows how I build inspectable records and explain system behavior.',
    priorities: [priority('Financial state', 'Represent what an operation means before implementing its transitions.'), priority('Developer clarity', 'Explain assumptions and failure cases through concrete examples.'), priority('Business economics', 'Connect a technical workflow with costs, incentives, and cash flow.')],
    work: ['payrollpro', 'atlas', 'markets'],
    reading: [reading.sqlite, reading.loyalty],
    experience: ['VOID Agency', 'Chegg, Inc.', 'Jon Brumley Texas Venture Labs'],
  },
  ramp: {
    focus: 'Finance operations & usable software',
    headline: ['Follow the spend.', 'Improve the decision.'],
    introduction: 'For Ramp, I selected finance and product work together. I run a small business, build operating tools, and study how clearer records and assumptions can improve a financial decision.',
    priorities: [priority('Operating context', 'Understand the task and the person responsible for the next action.'), priority('Financial comparisons', 'Expose the cost assumptions behind an option or recommendation.'), priority('Workflow usability', 'Reduce ambiguity in records, status, and approval steps.')],
    work: ['markets', 'payrollpro', 'internshipdeadlines'],
    reading: [reading.loyalty, reading.homeServices],
    experience: ['VOID Agency', 'Jon Brumley Texas Venture Labs', 'InternshipDeadlines'],
  },
  coinbase: {
    focus: 'Digital assets, strategy & product',
    headline: ['Understand the market.', 'Build for its users.'],
    introduction: 'For Coinbase, I selected digital-asset research and product work. My institutional client strategy submission was among 20 winning entries in the June 2026 Coinbase challenge; PayrollPro adds a concrete prototype to that interest.',
    priorities: [priority('Client strategy', 'Connect a customer segment with a clear product and commercial case.'), priority('Market structure', 'Examine valuation, incentives, and risk alongside the technology.'), priority('Working evidence', 'Use a prototype or source-backed analysis to make an idea reviewable.')],
    work: ['markets', 'payrollpro', 'internshipdeadlines'],
    reading: [reading.index, reading.loyalty],
    experience: financeExperience,
  },
  robinhood: {
    focus: 'Consumer finance & product clarity',
    headline: ['Complex markets.', 'Clearer choices.'],
    introduction: 'For Robinhood, I selected work that connects financial understanding with a consumer interface. I study market structure and build products that help someone compare options without losing the assumptions behind them.',
    priorities: [priority('Decision clarity', 'Explain a comparison in terms a user can inspect and question.'), priority('Consumer workflows', 'Connect discovery, information, and the next meaningful action.'), priority('Market research', 'Trace the incentives and mechanics behind a financial claim.')],
    work: ['internshipdeadlines', 'markets', 'payrollpro'],
    reading: [reading.index, reading.loyalty],
    experience: ['Chegg, Inc.', 'Jon Brumley Texas Venture Labs', 'InternshipDeadlines'],
  },
  'base-power': {
    focus: 'Energy, operations & commercial product',
    headline: ['Physical constraints.', 'Commercial possibilities.'],
    introduction: 'For Base Power, I selected my energy research, financial modeling, and product work. I’m interested in how physical capacity, customer economics, and operating decisions fit together—and in making those tradeoffs understandable.',
    priorities: [priority('Energy economics', 'Translate capacity and utilization assumptions into a financial model.'), priority('Customer questions', 'Connect pricing and messaging with what a buyer needs to understand.'), priority('Operating tools', 'Turn source records and models into a usable decision workflow.')],
    work: ['markets', 'sapien', 'atlas'],
    reading: [reading.power, reading.hardware],
    experience: commercialExperience,
  },
  anduril: {
    focus: 'Industrial systems & commercial analysis',
    headline: ['From the requirement', 'to the operating reality.'],
    introduction: 'For Anduril, I selected work on hardware financing, industrial constraints, and software systems. I’m drawn to the commercial questions behind a physical product: capacity, capital, dependencies, and execution.',
    priorities: [priority('Industrial economics', 'Distinguish a product thesis from the resources needed to deliver it.'), priority('Evidence systems', 'Keep assumptions and source records available for inspection.'), priority('Clear recommendations', 'Connect technical context with a specific commercial decision.')],
    work: ['markets', 'atlas', 'solver'],
    reading: [reading.hardware, reading.magnets],
    experience: financeExperience,
  },
  tesla: {
    focus: 'Energy, manufacturing & customer economics',
    headline: ['A physical product.', 'A whole economic system.'],
    introduction: 'For Tesla, I selected research on energy capacity, hardware capital, and buyer decisions. My work combines financial analysis with product and growth, giving me a way to examine both the system and the customer.',
    priorities: [priority('Physical capacity', 'Make the gap between nameplate capacity and usable output explicit.'), priority('Customer economics', 'Frame pricing and product questions around a defined use case.'), priority('Capital needs', 'Trace the financing and dependencies behind hardware delivery.')],
    work: ['markets', 'sapien', 'internshipdeadlines'],
    reading: [reading.power, reading.magnets],
    experience: commercialExperience,
  },
  waymo: {
    focus: 'Mobility economics & operating systems',
    headline: ['The ride has', 'a capital stack.'],
    introduction: 'For Waymo, I would begin with my published research on who funds the hardware. The broader connection is my interest in the relationship between a physical service, its financing, and the operating choices that follow.',
    priorities: [priority('Capital structure', 'Trace which party owns the asset, supplies capital, and bears risk.'), priority('Operating assumptions', 'Connect utilization and costs with the economics of a service.'), priority('Source-backed analysis', 'Make claims inspectable through the records supporting them.')],
    work: ['markets', 'atlas', 'solver'],
    reading: [reading.waymo, reading.hardware],
    experience: financeExperience,
  },
  skydio: {
    focus: 'Autonomous systems & product strategy',
    headline: ['Technical capability.', 'A useful deployment.'],
    introduction: 'For Skydio, I selected work on evaluating systems and understanding hardware economics. I’m interested in the path from a technical capability to a customer workflow, with evidence that explains the limits as well as the promise.',
    priorities: [priority('Use-case definition', 'Turn a broad capability into a concrete customer task.'), priority('Evaluation discipline', 'Define what a successful test establishes and what remains unknown.'), priority('Hardware economics', 'Connect deployment choices with capital and operating requirements.')],
    work: ['solver', 'markets', 'atlas'],
    reading: [reading.hardware, reading.traces],
    experience: ['Chegg, Inc.', 'Jon Brumley Texas Venture Labs', 'VOID Agency'],
  },
  zipline: {
    focus: 'Delivery systems & operating economics',
    headline: ['A delivery promise.', 'An operating model.'],
    introduction: 'For Zipline, I selected research that follows a physical service through its costs and constraints. My product work adds another perspective: making the workflow useful to the person relying on it.',
    priorities: [priority('Service economics', 'Map the cost and utilization assumptions behind delivery.'), priority('Workflow reliability', 'Make status, interrupted steps, and unresolved information visible.'), priority('Customer usefulness', 'Connect the operating system with the task a customer needs completed.')],
    work: ['markets', 'atlas', 'internshipdeadlines'],
    reading: [reading.hardware, reading.returns],
    experience: ['Jon Brumley Texas Venture Labs', 'VOID Agency', 'InternshipDeadlines'],
  },
  'ge-vernova': {
    focus: 'Energy infrastructure & financial analysis',
    headline: ['Follow the power.', 'Follow the economics.'],
    introduction: 'For GE Vernova, I selected research on energy capacity and infrastructure cash flows. I study how physical limits, financing, and operating assumptions change the economic meaning of a headline number.',
    priorities: [priority('Capacity analysis', 'Distinguish installed capacity, usable power, and utilization.'), priority('Infrastructure finance', 'Trace revenue rights, costs, and debt-service assumptions.'), priority('Decision communication', 'Explain which assumption drives a result and why it matters.')],
    work: ['markets', 'atlas', 'solver'],
    reading: [reading.power, reading.tollCash],
    experience: financeExperience,
  },
  'texas-instruments': {
    focus: 'Industrial economics & technical communication',
    headline: ['Small components.', 'Large system consequences.'],
    introduction: 'For Texas Instruments, I selected work on industrial capacity and the commercial logic of technical products. I enjoy turning a complicated system into a clear account of its constraints, economics, and customer use.',
    priorities: [priority('Industry research', 'Separate announced capacity from facilities and output that exist.'), priority('Commercial context', 'Connect technical capabilities with the customer’s operating problem.'), priority('Structured analysis', 'Build comparable records before drawing an industry conclusion.')],
    work: ['markets', 'atlas', 'sapien'],
    reading: [reading.magnets, reading.power],
    experience: ['Jon Brumley Texas Venture Labs', 'Sapien', 'VOID Agency'],
  },
  amd: {
    focus: 'Compute economics & AI applications',
    headline: ['More compute.', 'A clearer use case.'],
    introduction: 'For AMD, I selected research on AI power requirements alongside hands-on AI applications. I’m interested in how the economics of compute connect with the product someone can actually use.',
    priorities: [priority('Compute assumptions', 'Connect utilization and overhead with usable capacity.'), priority('Application judgment', 'Evaluate model behavior against a task rather than a general promise.'), priority('Commercial explanation', 'Translate technical tradeoffs into a concrete buyer question.')],
    work: ['markets', 'internshipdeadlines', 'solver'],
    reading: [reading.power, reading.traces],
    experience: aiExperience,
  },
  vertiv: {
    focus: 'Data-center infrastructure & operating analysis',
    headline: ['Capacity on paper.', 'Capacity in operation.'],
    introduction: 'For Vertiv, my AI-megawatt research is the starting point. I examine how overhead, utilization, and the definition of a capacity number affect the economic conclusions someone draws from it.',
    priorities: [priority('Capacity definitions', 'Make the measurement boundary explicit before comparing power claims.'), priority('Scenario models', 'Show how operating assumptions change usable output and economics.'), priority('Evidence quality', 'Keep calculations connected to their inputs and source definitions.')],
    work: ['markets', 'atlas', 'solver'],
    reading: [reading.power, reading.hardware],
    experience: financeExperience,
  },
  'goldman-sachs': {
    focus: 'Financial research & commercial judgment',
    headline: ['Understand the structure.', 'Explain the exposure.'],
    introduction: 'For Goldman Sachs, I selected my work on capital stacks, revenue rights, and investment questions. I study finance at UT Austin and build models that connect a commercial thesis with its assumptions and risks.',
    priorities: [priority('Financial structure', 'Trace ownership, financing, and the rights attached to cash flows.'), priority('Investment research', 'Separate a persuasive narrative from a supported economic conclusion.'), priority('Clear analysis', 'Make the model and the recommendation understandable together.')],
    work: ['markets', 'solver', 'atlas'],
    reading: [reading.hardware, reading.loyalty],
    experience: financeExperience,
  },
  jpmorgan: {
    focus: 'Finance, operating models & product',
    headline: ['Financial judgment.', 'Systems that support it.'],
    introduction: 'For JPMorgan, I selected finance research alongside tools for reliable information. My work connects cash-flow analysis with the practical problem of collecting, structuring, and explaining the evidence behind a decision.',
    priorities: [priority('Cash-flow analysis', 'Connect revenue definitions and financing terms with the resulting exposure.'), priority('Information quality', 'Retain source history while transforming data into a useful record.'), priority('Business workflows', 'Understand how an analysis becomes an operating or client decision.')],
    work: ['markets', 'atlas', 'payrollpro'],
    reading: [reading.loyalty, reading.tollCash],
    experience: financeExperience,
  },
  'capital-one': {
    focus: 'Consumer finance, analytics & product',
    headline: ['Good analysis.', 'A better customer choice.'],
    introduction: 'For Capital One, I selected work combining finance, analytics, and consumer product design. Chegg and InternshipDeadlines show how I use research and structured data to help a person make a clearer decision.',
    priorities: [priority('Customer decisions', 'Understand the question before building the comparison or recommendation.'), priority('Data products', 'Connect classification and ranking with a usable customer workflow.'), priority('Financial assumptions', 'Make the costs and tradeoffs behind an answer inspectable.')],
    work: ['internshipdeadlines', 'markets', 'sapien'],
    reading: [reading.loyalty, reading.index],
    experience: ['Chegg, Inc.', 'InternshipDeadlines', 'Jon Brumley Texas Venture Labs'],
  },
  blackrock: {
    focus: 'Investment research & structured data',
    headline: ['From market mechanics', 'to an investment question.'],
    introduction: 'For BlackRock, I selected research on index mechanics, infrastructure, and financial claims. I’m interested in how a market rule or ownership structure changes the flows and risks an investor needs to understand.',
    priorities: [priority('Market mechanics', 'Trace the mechanism between a rule, a flow, and an economic effect.'), priority('Research records', 'Build comparable evidence before aggregating or interpreting it.'), priority('Risk framing', 'State what the data supports and where inference begins.')],
    work: ['markets', 'atlas', 'solver'],
    reading: [reading.index, reading.tollOwnership],
    experience: financeExperience,
  },
  blackstone: {
    focus: 'Private markets & asset economics',
    headline: ['The asset.', 'The cash-flow rights.'],
    introduction: 'For Blackstone, I selected my work on real assets, financing, and ownership. My research follows the distinction between owning a physical asset and holding the economic rights that make it an investment.',
    priorities: [priority('Asset structure', 'Trace ownership, control, financing, and operating responsibilities separately.'), priority('Operating economics', 'Compare revenue and cost definitions on a consistent basis.'), priority('Downside analysis', 'Make the assumptions behind value and liquidity visible.')],
    work: ['markets', 'atlas', 'sapien'],
    reading: [reading.housing, reading.buyouts],
    experience: financeExperience,
  },
  kkr: {
    focus: 'Investment diligence & business operations',
    headline: ['Test the thesis.', 'Understand the business.'],
    introduction: 'For KKR, I selected research on buyouts and hardware capital alongside commercial work. I like examining both sides of an investment question: the financial structure and the operating business underneath it.',
    priorities: [priority('Diligence questions', 'Turn a broad thesis into assumptions that can be checked.'), priority('Exit analysis', 'Distinguish a control exit from a financing or liquidity event.'), priority('Commercial drivers', 'Connect pricing, positioning, and customer needs with the model.')],
    work: ['markets', 'sapien', 'atlas'],
    reading: [reading.buyouts, reading.hardware],
    experience: commercialExperience,
  },
  apollo: {
    focus: 'Capital structures & cash-flow analysis',
    headline: ['Who supplies capital?', 'Who bears the risk?'],
    introduction: 'For Apollo, I selected research on financing structures and claims on cash flow. My work examines who supplies capital, which rights they receive, and what happens to the economics when assumptions change.',
    priorities: [priority('Capital claims', 'Map debt, ownership, and contractual rights without conflating them.'), priority('Cash-flow definitions', 'Use a consistent revenue basis before making coverage comparisons.'), priority('Scenario analysis', 'Show the changes that matter to liquidity and repayment.')],
    work: ['markets', 'solver', 'atlas'],
    reading: [reading.loyalty, reading.tollCash],
    experience: financeExperience,
  },
  'jane-street': {
    focus: 'Exact reasoning, verification & markets',
    headline: ['Find the solution.', 'Verify the search.'],
    introduction: 'For Jane Street, I would start with my exact-search solver and its verification record. I was listed among the correct solvers of the July 2026 monthly puzzle; the published study explains the reasoning and checks behind the result.',
    priorities: [priority('Exact reasoning', 'Translate the problem into states, constraints, and a checkable result.'), priority('Independent checks', 'Verify the solution and the search rather than trust a successful run.'), priority('Market curiosity', 'Study the mechanics and incentives behind financial outcomes.')],
    work: ['solver', 'markets', 'atlas'],
    reading: [reading.solver, reading.index],
    experience: ['Chegg, Inc.', 'Jon Brumley Texas Venture Labs', 'VOID Agency'],
  },
  'citadel-securities': {
    focus: 'Market structure & quantitative reasoning',
    headline: ['Understand the mechanism.', 'Check the result.'],
    introduction: 'For Citadel Securities, I selected work on market mechanics and exact verification. My finance research asks how rules affect flows; my solver work shows how I make a computational conclusion independently checkable.',
    priorities: [priority('Mechanism analysis', 'Connect a market rule with the behavior and flows it can create.'), priority('Quantitative checks', 'Define invariants and independently verify the result.'), priority('Data discipline', 'Preserve the source and transformation history of a research record.')],
    work: ['solver', 'markets', 'atlas'],
    reading: [reading.solver, reading.index],
    experience: ['Chegg, Inc.', 'Jon Brumley Texas Venture Labs', 'InternshipDeadlines'],
  },
  'd-e-shaw': {
    focus: 'Research systems & computational reasoning',
    headline: ['A research question.', 'A reproducible answer.'],
    introduction: 'For D. E. Shaw, I selected the computational side of my research. Exact search, structured evidence, and financial analysis share a working habit: make the question precise enough that the answer can be tested.',
    priorities: [priority('Problem formulation', 'Define the state, assumptions, and objective before choosing the method.'), priority('Reproducibility', 'Retain the inputs and checks needed to inspect a conclusion.'), priority('Research judgment', 'Separate a measured result from the interpretation built on it.')],
    work: ['solver', 'atlas', 'markets'],
    reading: [reading.solver, reading.sqlite],
    experience: ['Chegg, Inc.', 'VOID Agency', 'Jon Brumley Texas Venture Labs'],
  },
  'bridgewater-associates': {
    focus: 'Financial systems & explicit assumptions',
    headline: ['Make the assumptions', 'part of the argument.'],
    introduction: 'For Bridgewater, I selected research that starts with a mechanism and follows its consequences. Energy constraints, financing structures, and index rules give me concrete ways to examine how a financial system behaves.',
    priorities: [priority('System mechanisms', 'Explain the causal path between a rule, a constraint, and an outcome.'), priority('Model transparency', 'Show which assumptions change the conclusion and by how much.'), priority('Evidence boundaries', 'Keep observations separate from scenarios and inferred explanations.')],
    work: ['markets', 'solver', 'atlas'],
    reading: [reading.power, reading.index],
    experience: financeExperience,
  },
  vanguard: {
    focus: 'Investment mechanics & investor clarity',
    headline: ['Understand the index.', 'Explain the investment.'],
    introduction: 'For Vanguard, I selected my research on index inclusion and the structure of financial claims. I’m interested in making the mechanics behind an investment clear enough that someone can understand the exposure they are taking.',
    priorities: [priority('Index mechanics', 'Examine the link between methodology, inclusion, and investor flows.'), priority('Clear explanation', 'Make definitions and assumptions accessible without losing their meaning.'), priority('Research consistency', 'Compare financial records on a like-for-like basis.')],
    work: ['markets', 'atlas', 'internshipdeadlines'],
    reading: [reading.index, reading.loyalty],
    experience: financeExperience,
  },
  mckinsey: {
    focus: 'Strategy, commercial research & implementation',
    headline: ['Frame the question.', 'Build the answer.'],
    introduction: 'For McKinsey, I selected work that connects analysis with execution. At Texas Venture Labs I research markets and unit economics; through VOID and Sapien I turn commercial questions into models, tools, and usable material.',
    priorities: [priority('Problem framing', 'Define the decision and the evidence needed before collecting more data.'), priority('Commercial analysis', 'Connect customer needs, pricing, and unit economics.'), priority('Implementation', 'Make recommendations concrete through a working tool or deliverable.')],
    work: ['markets', 'sapien', 'atlas'],
    reading: [reading.homeServices, reading.power],
    experience: commercialExperience,
  },
  bain: {
    focus: 'Commercial diligence & growth',
    headline: ['Understand demand.', 'Test the value case.'],
    introduction: 'For Bain, I selected my commercial research, pricing, and buyout work. I enjoy connecting a company’s customer proposition with the assumptions that make its growth and investment case credible.',
    priorities: [priority('Customer research', 'Start with the buying decision and the evidence of demand.'), priority('Commercial diligence', 'Test pricing, positioning, and market assumptions together.'), priority('Value creation', 'Translate a conclusion into a specific operating or growth action.')],
    work: ['sapien', 'markets', 'internshipdeadlines'],
    reading: [reading.buyouts, reading.homeServices],
    experience: commercialExperience,
  },
  'k1-investment-management': {
    focus: 'Software investing & commercial operations',
    headline: ['A software product.', 'A business worth understanding.'],
    introduction: 'For K1, I selected software-building experience alongside buyout and commercial research. I can examine a product as a user workflow, then ask how its pricing, customers, and operating model support the investment case.',
    priorities: [priority('Product diligence', 'Understand the customer task and the value the software delivers.'), priority('Growth drivers', 'Connect buyer use cases and positioning with commercial assumptions.'), priority('Exit evidence', 'Classify transaction outcomes consistently before drawing conclusions.')],
    work: ['internshipdeadlines', 'sapien', 'markets'],
    reading: [reading.buyouts, reading.managers],
    experience: commercialExperience,
  },
  'hq-capital': {
    focus: 'Private-market research & investment records',
    headline: ['Comparable evidence.', 'Better investment questions.'],
    introduction: 'For HQ Capital, I selected private-market research and structured evidence work. My buyout audit examines transaction outcomes carefully; Atlas shows the record discipline I bring to a larger research process.',
    priorities: [priority('Comparable outcomes', 'Use explicit definitions when classifying liquidity and control events.'), priority('Research records', 'Keep transaction claims attached to dated sources.'), priority('Investment communication', 'Explain the conclusion, assumptions, and missing evidence together.')],
    work: ['markets', 'atlas', 'solver'],
    reading: [reading.buyouts, reading.hardware],
    experience: financeExperience,
  },
  riveron: {
    focus: 'Financial advisory & operating information',
    headline: ['Clearer numbers.', 'An actionable next step.'],
    introduction: 'For Riveron, I selected financial analysis and practical systems work. My experience spans operating plans, business models, and tools that turn source information into reviewable findings and decisions.',
    priorities: [priority('Financial definitions', 'Clarify what a number represents before using it in a comparison.'), priority('Operating context', 'Connect analysis with the workflow and decisions it must support.'), priority('Usable deliverables', 'Make recommendations traceable and specific enough to act on.')],
    work: ['markets', 'atlas', 'sapien'],
    reading: [reading.tollCash, reading.findings],
    experience: financeExperience,
  },
  'pzena-investment-management': {
    focus: 'Fundamental research & business economics',
    headline: ['Look through the story.', 'Understand the earnings.'],
    introduction: 'For Pzena, I selected research focused on business economics and the assumptions behind value. I like tracing how ownership, costs, financing, and operating conditions affect the cash flows underneath a market narrative.',
    priorities: [priority('Business fundamentals', 'Study the operating drivers before accepting the investment story.'), priority('Assumption testing', 'Identify what must improve for an economic thesis to hold.'), priority('Patient research', 'Build a sourced record that can be revisited as facts change.')],
    work: ['markets', 'atlas', 'solver'],
    reading: [reading.buyouts, reading.loyalty],
    experience: financeExperience,
  },
  massmutual: {
    focus: 'Long-term finance & customer understanding',
    headline: ['A long-term commitment.', 'Clear assumptions today.'],
    introduction: 'For MassMutual, I selected work on financial obligations and understandable decisions. My finance background and consumer-product work help me examine both the structure of a commitment and the person making it.',
    priorities: [priority('Financial obligations', 'Trace the cash flows, assumptions, and risks over time.'), priority('Customer clarity', 'Explain a comparison without hiding the conditions behind it.'), priority('Research discipline', 'Keep a recommendation connected to its source evidence.')],
    work: ['markets', 'internshipdeadlines', 'atlas'],
    reading: [reading.loyalty, reading.tollCash],
    experience: ['Jon Brumley Texas Venture Labs', 'Chegg, Inc.', 'VOID Agency'],
  },
  'plante-moran': {
    focus: 'Business advisory & financial analysis',
    headline: ['Understand the business.', 'Make the analysis useful.'],
    introduction: 'For Plante Moran, I selected my operating-plan, financial-modeling, and source-review work. Running VOID gives me direct small-business context; Texas Venture Labs adds experience framing commercial questions for founders.',
    priorities: [priority('Business context', 'Begin with the decision an owner or operating team needs to make.'), priority('Model clarity', 'Keep revenue, costs, and assumptions understandable together.'), priority('Reviewable evidence', 'Make the path from source records to recommendations explicit.')],
    work: ['markets', 'atlas', 'sapien'],
    reading: [reading.homeServices, reading.tollCash],
    experience: ['VOID Agency', 'Jon Brumley Texas Venture Labs', 'Sapien'],
  },
  'northwood-space': {
    focus: 'Space communications & infrastructure economics',
    headline: ['The ground layer', 'has its own economics.'],
    introduction: 'For Northwood Space, I selected infrastructure research and systems work. The ground-network problem interests me because hardware, scheduling, utilization, and customer needs have to become one coherent operating model.',
    priorities: [priority('Infrastructure economics', 'Connect physical capacity and utilization with costs and customer value.'), priority('Operating records', 'Make resource status and the next action explicit.'), priority('Commercial research', 'Translate a technical system into a defined customer use case.')],
    work: ['markets', 'atlas', 'sapien'],
    reading: [reading.hardware, reading.power],
    experience: commercialExperience,
  },
  'dalio-family-office': {
    focus: 'Investment research & system-level reasoning',
    headline: ['Trace the mechanism.', 'Challenge the assumption.'],
    introduction: 'For the Dalio Family Office, I selected work on financial systems, capital structures, and rigorous problem-solving. My research habit is to trace the mechanism behind a claim and make the assumptions available for review.',
    priorities: [priority('System reasoning', 'Connect economic rules and physical constraints with their consequences.'), priority('Investment questions', 'Examine ownership, risk, and cash-flow rights together.'), priority('Research tools', 'Use structured records and explicit checks to improve an analysis.')],
    work: ['markets', 'solver', 'atlas'],
    reading: [reading.power, reading.index],
    experience: financeExperience,
  },
  'muon-space': {
    focus: 'Space systems & data-product strategy',
    headline: ['From a mission', 'to a useful decision.'],
    introduction: 'For Muon Space, I selected work connecting technical systems with the value of their data. Atlas and InternshipDeadlines both turn collected records into useful decisions; my finance research adds a view of the capital behind a physical system.',
    priorities: [priority('Data usefulness', 'Define the customer decision before designing the information product.'), priority('System economics', 'Connect a physical capability with its costs and operating assumptions.'), priority('Source integrity', 'Retain provenance as collected information becomes an interpretation.')],
    work: ['atlas', 'markets', 'internshipdeadlines'],
    reading: [reading.hardware, reading.infrastructure],
    experience: ['VOID Agency', 'InternshipDeadlines', 'Jon Brumley Texas Venture Labs'],
  },
  amca: {
    focus: 'Industrial capacity & business systems',
    headline: ['A critical component.', 'A chain of dependencies.'],
    introduction: 'For Amca, I selected research on industrial capacity, capital, and the records behind a claim. I’m interested in the business questions around aerospace components: dependencies, production readiness, and the economics of expanding supply.',
    priorities: [priority('Capacity evidence', 'Distinguish a plan, a qualified facility, and delivered output.'), priority('Industrial economics', 'Map capital needs and operating dependencies before comparing opportunities.'), priority('Information systems', 'Keep supplier and capacity claims connected to their source records.')],
    work: ['markets', 'atlas', 'solver'],
    reading: [reading.magnets, reading.hardware],
    experience: financeExperience,
  },
  'k2-space': {
    focus: 'Space hardware & commercial analysis',
    headline: ['Bigger hardware.', 'Explicit economics.'],
    introduction: 'For K2 Space, I selected research on physical capacity and hardware financing. Satellite scale interests me as a commercial question: how power, manufacturing, utilization, and capital requirements affect what a system makes possible.',
    priorities: [priority('Physical tradeoffs', 'Translate changes in capacity into an explicit operating scenario.'), priority('Capital requirements', 'Trace how hardware is financed and which risks follow each structure.'), priority('Commercial use cases', 'Connect a technical capability with a customer’s concrete need.')],
    work: ['markets', 'atlas', 'sapien'],
    reading: [reading.hardware, reading.power],
    experience: commercialExperience,
  },
  'charles-river-associates': {
    focus: 'Economic research & analytical evidence',
    headline: ['A precise question.', 'A defensible analysis.'],
    introduction: 'For Charles River Associates, I selected work that makes economic reasoning inspectable. My research traces market mechanisms and financial rights; my solver and Atlas work add explicit checks and structured evidence.',
    priorities: [priority('Economic mechanisms', 'Explain the path from an assumption or rule to an outcome.'), priority('Data definitions', 'Make populations, categories, and comparison bases explicit.'), priority('Analytical checks', 'Retain the sources and tests needed to review a conclusion.')],
    work: ['markets', 'solver', 'atlas'],
    reading: [reading.index, reading.tollOwnership],
    experience: financeExperience,
  },
  'precision-aq-precision-medicine-group': {
    focus: 'Commercial research & evidence communication',
    headline: ['Complex evidence.', 'A clear commercial question.'],
    introduction: 'For Precision AQ, I selected my research synthesis, pricing, and buyer-communication work. At Sapien I explain research methods and their limits; at Texas Venture Labs I connect market questions with commercial models.',
    priorities: [priority('Research interpretation', 'Explain what a study establishes and what its method cannot answer.'), priority('Commercial questions', 'Frame pricing and positioning around a defined audience and decision.'), priority('Clear communication', 'Make technical evidence understandable without overstating its strength.')],
    work: ['sapien', 'markets', 'atlas'],
    reading: [reading.findings, reading.managers],
    experience: commercialExperience,
  },
  'link-logistics': {
    focus: 'Logistics real estate & operating economics',
    headline: ['A physical network.', 'A financial model.'],
    introduction: 'For Link Logistics, I selected work on real assets and the economics of moving goods. My research on ownership and returns gives me a way to connect a property’s financial structure with the operating activity it supports.',
    priorities: [priority('Asset economics', 'Connect ownership, financing, and utilization with the operating model.'), priority('Logistics questions', 'Trace the costs and decisions behind the movement of goods.'), priority('Comparable records', 'Keep definitions consistent when comparing facilities or businesses.')],
    work: ['markets', 'atlas', 'sapien'],
    reading: [reading.returns, reading.housing],
    experience: financeExperience,
  },
  'related-companies': {
    focus: 'Real estate, capital & market research',
    headline: ['Understand the place.', 'Understand the capital.'],
    introduction: 'For Related Companies, I selected my property-ownership research and financial analysis. I’m interested in the connection between a place’s commercial use, the capital behind it, and the rights and obligations of its owners.',
    priorities: [priority('Ownership structures', 'Separate title, control, financing, and operating responsibilities.'), priority('Market assumptions', 'Connect the use of a property with a defined demand and pricing case.'), priority('Financial scenarios', 'Make the drivers of cash flow and downside visible.')],
    work: ['markets', 'sapien', 'atlas'],
    reading: [reading.housing, reading.tollOwnership],
    experience: commercialExperience,
  },
  'alvarez-and-marsal': {
    focus: 'Business performance & financial structure',
    headline: ['Find the constraint.', 'Build the operating answer.'],
    introduction: 'For Alvarez & Marsal, I selected analysis that connects financial structure with operating reality. My work spans buyout outcomes, cash-flow models, and software tools that make the underlying records usable.',
    priorities: [priority('Business diagnosis', 'Identify which operating or financial assumption is driving the problem.'), priority('Financial structure', 'Trace liquidity, control, and cash-flow claims separately.'), priority('Practical execution', 'Turn findings into a specific tool, model, or operating recommendation.')],
    work: ['markets', 'atlas', 'sapien'],
    reading: [reading.buyouts, reading.tollCash],
    experience: ['VOID Agency', 'Jon Brumley Texas Venture Labs', 'Sapien'],
  },
  greystar: {
    focus: 'Housing economics & customer research',
    headline: ['A place to live.', 'A business to understand.'],
    introduction: 'For Greystar, I selected my West Campus housing research and buyer-focused work. I study how ownership and financing shape a property while also asking what its customer needs to understand and choose.',
    priorities: [priority('Housing economics', 'Connect ownership and capital structure with the property’s cash flows.'), priority('Customer perspective', 'Frame pricing and positioning around a concrete housing decision.'), priority('Source research', 'Make property and ownership claims traceable to dated evidence.')],
    work: ['markets', 'sapien', 'internshipdeadlines'],
    reading: [reading.housing, reading.homeServices],
    experience: commercialExperience,
  },
  berrydunn: {
    focus: 'Advisory, analysis & public-sector systems',
    headline: ['A clearer record.', 'A more useful recommendation.'],
    introduction: 'For BerryDunn, I selected work that turns complicated records into usable analysis. Infrastructure research and Atlas both require clear definitions, retained sources, and a recommendation someone else can inspect.',
    priorities: [priority('Source review', 'Keep the facts behind a finding available to the reviewer.'), priority('Financial comparability', 'Define revenue and cost measures before comparing entities.'), priority('Operating recommendations', 'Connect the analysis with an explicit decision and next step.')],
    work: ['atlas', 'markets', 'internshipdeadlines'],
    reading: [reading.tollCash, reading.findings],
    experience: ['VOID Agency', 'Jon Brumley Texas Venture Labs', 'Chegg, Inc.'],
  },
  bwxt: {
    focus: 'Energy, industrial capacity & business analysis',
    headline: ['Long-lived systems.', 'Careful assumptions.'],
    introduction: 'For BWXT, I selected my work on energy capacity and industrial economics. I’m interested in the business analysis around nuclear infrastructure: physical constraints, capital requirements, and the distinction between plans and operating capacity.',
    priorities: [priority('Capacity definitions', 'Separate announced output from capacity that is available in operation.'), priority('Capital analysis', 'Connect a physical system’s requirements with financing and timing.'), priority('Evidence discipline', 'Make the basis and limits of an industrial claim explicit.')],
    work: ['markets', 'atlas', 'solver'],
    reading: [reading.power, reading.magnets],
    experience: financeExperience,
  },
  'keurig-dr-pepper': {
    focus: 'Consumer insights, pricing & growth',
    headline: ['A consumer choice.', 'A commercial question.'],
    introduction: 'For Keurig Dr Pepper, I selected my consumer-research and positioning work. At Sapien, I develop buyer use cases around pricing, concept testing, and messaging, with careful distinctions between modeled responses and observed behavior.',
    priorities: [priority('Consumer questions', 'Frame a study around the choice a person is making.'), priority('Pricing and concepts', 'Compare alternatives under explicit assumptions and a defined audience.'), priority('Evidence-led messaging', 'Turn research into clear creative and commercial material.')],
    work: ['sapien', 'creative', 'markets'],
    reading: [reading.viralbench, reading.returns],
    experience: ['Sapien', 'CreativeTrace', 'Jon Brumley Texas Venture Labs'],
  },
  'moet-hennessy-usa-lvmh': {
    focus: 'Brand strategy, consumer research & creative',
    headline: ['Know the audience.', 'Respect the brand.'],
    introduction: 'For Moët Hennessy, I selected work on positioning, creative research, and how people respond to a message. I connect a commercial question with the evidence and creative choices needed to explain a product’s value.',
    priorities: [priority('Audience understanding', 'Develop a precise question about the buyer, occasion, or message.'), priority('Positioning', 'Connect a product’s value with the language used to explain it.'), priority('Creative judgment', 'Use source-linked hypotheses to guide concepts and experimentation.')],
    work: ['sapien', 'creative', 'markets'],
    reading: [reading.viralbench, reading.loyalty],
    experience: ['Sapien', 'CreativeTrace', 'AI Image Generation Startup'],
  },
  bcg: {
    focus: 'Strategy, research & product execution',
    headline: ['A sharper question.', 'A working response.'],
    introduction: 'For BCG, I selected work that combines strategy with building. My experience spans market and pricing research, AI product workflows, and growth material that turns complex evidence into a useful commercial explanation.',
    priorities: [priority('Strategic framing', 'Identify the decision and the assumptions that could change it.'), priority('Analytical synthesis', 'Connect market, customer, and financial evidence in one argument.'), priority('Product execution', 'Use a working tool or experiment to make a recommendation concrete.')],
    work: ['sapien', 'markets', 'internshipdeadlines'],
    reading: [reading.power, reading.managers],
    experience: ['Jon Brumley Texas Venture Labs', 'Chegg, Inc.', 'Sapien'],
  },
  'state-farm': {
    focus: 'Customer decisions, risk & digital product',
    headline: ['Understand the risk.', 'Help the customer decide.'],
    introduction: 'For State Farm, I selected work connecting complex choices with clear customer workflows. My finance studies and student-product experience give me a way to examine assumptions while keeping the person making the decision in view.',
    priorities: [priority('Customer research', 'Understand the question, constraints, and information a person needs.'), priority('Risk communication', 'Explain conditions and tradeoffs without hiding the assumptions.'), priority('Digital workflows', 'Connect information, status, and the next useful action.')],
    work: ['internshipdeadlines', 'markets', 'sapien'],
    reading: [reading.homeServices, reading.loyalty],
    experience: ['Chegg, Inc.', 'Jon Brumley Texas Venture Labs', 'Sapien'],
  },
  ghj: {
    focus: 'Financial advisory & business understanding',
    headline: ['Know what the number', 'is telling you.'],
    introduction: 'For GHJ, I selected financial analysis and the practical context of running a business. I enjoy clarifying definitions, tracing source records, and connecting a model with the operating decision it is meant to support.',
    priorities: [priority('Financial clarity', 'Define the measure and its assumptions before using it.'), priority('Owner perspective', 'Connect analysis with the needs of an operating business.'), priority('Reviewable work', 'Make supporting records and the reasoning behind recommendations accessible.')],
    work: ['markets', 'atlas', 'sapien'],
    reading: [reading.homeServices, reading.loyalty],
    experience: ['VOID Agency', 'Jon Brumley Texas Venture Labs', 'Sapien'],
  },
  kyndryl: {
    focus: 'Enterprise systems & reliable workflows',
    headline: ['Understand the system.', 'Make the change concrete.'],
    introduction: 'For Kyndryl, I selected work on system behavior, evidence, and practical implementation. Atlas and my web-systems work emphasize inspectable records, explicit failure states, and checking the result at the delivery boundary.',
    priorities: [priority('System understanding', 'Map the dependencies and contracts before changing a workflow.'), priority('Operational evidence', 'Keep failures, missing data, and partial results visible.'), priority('Verified delivery', 'Check the behavior someone can use rather than only the implementation.')],
    work: ['atlas', 'internshipdeadlines', 'solver'],
    reading: [reading.releases, reading.frontier],
    experience: systemsExperience,
  },
  'berkeley-research-group-brg': {
    focus: 'Economic research & analytical rigor',
    headline: ['Make the claim', 'stand up to inspection.'],
    introduction: 'For Berkeley Research Group, I selected work on economic mechanisms and evidence quality. My research distinguishes ownership from cash-flow rights, and my systems work keeps the records behind a conclusion available for review.',
    priorities: [priority('Economic questions', 'Define the mechanism and the evidence that would support it.'), priority('Source discipline', 'Retain dated records and avoid treating missing evidence as a fact.'), priority('Clear argument', 'Explain observations, assumptions, and conclusions as distinct steps.')],
    work: ['markets', 'atlas', 'solver'],
    reading: [reading.tollOwnership, reading.index],
    experience: financeExperience,
  },
  'js-held-ocean-tomo': {
    focus: 'Valuation, rights & technical evidence',
    headline: ['A technical asset.', 'An economic claim.'],
    introduction: 'For J.S. Held and Ocean Tomo, I selected work at the intersection of technical evidence and financial rights. I’m interested in how a capability or asset becomes an economic claim—and how the evidence supporting that claim is reviewed.',
    priorities: [priority('Rights and value', 'Trace who controls an asset and which economic rights follow.'), priority('Technical interpretation', 'Explain system evidence without overstating what it establishes.'), priority('Reviewable analysis', 'Keep source material, assumptions, and valuation reasoning connected.')],
    work: ['markets', 'atlas', 'solver'],
    reading: [reading.loyalty, reading.hardware],
    experience: financeExperience,
  },
  trumid: {
    focus: 'Market workflows, data & product',
    headline: ['Market information.', 'A useful trading workflow.'],
    introduction: 'For Trumid, I selected product work alongside market-structure research. The connection is how information becomes a decision inside a workflow: what the record means, what the user needs, and which action follows.',
    priorities: [priority('Market mechanics', 'Study the rules and incentives behind a financial interaction.'), priority('Information product', 'Connect structured data with the decision a user is making.'), priority('Workflow design', 'Make context and next actions clear without obscuring complexity.')],
    work: ['markets', 'internshipdeadlines', 'atlas'],
    reading: [reading.index, reading.sqlite],
    experience: ['Jon Brumley Texas Venture Labs', 'Chegg, Inc.', 'InternshipDeadlines'],
  },
  'parametric-morgan-stanley-investment-management': {
    focus: 'Portfolio mechanics & systematic research',
    headline: ['A defined exposure.', 'A checkable implementation.'],
    introduction: 'For Parametric, I selected research on index mechanics alongside exact-search and data-system work. I’m interested in the path from an investment objective to explicit rules, implementation choices, and a result that can be checked.',
    priorities: [priority('Market exposure', 'Understand the mechanics behind an index or portfolio objective.'), priority('Systematic reasoning', 'Translate constraints into explicit rules and independent checks.'), priority('Research records', 'Preserve inputs and assumptions so the result can be reviewed.')],
    work: ['markets', 'solver', 'atlas'],
    reading: [reading.index, reading.solver],
    experience: ['Jon Brumley Texas Venture Labs', 'Chegg, Inc.', 'VOID Agency'],
  },
  'impulse-space': {
    focus: 'Space mobility & hardware economics',
    headline: ['A destination in orbit.', 'An operating case on Earth.'],
    introduction: 'For Impulse Space, I selected work on hardware capital and physical-service economics. Moving a payload is also a commercial problem: define the mission, understand the resources it requires, and connect the capability with a customer need.',
    priorities: [priority('Mission economics', 'Connect a physical task with its cost and utilization assumptions.'), priority('Capital structure', 'Trace how hardware requirements affect financing and delivery.'), priority('Commercial definition', 'Turn a technical capability into a specific customer use case.')],
    work: ['markets', 'atlas', 'sapien'],
    reading: [reading.hardware, reading.waymo],
    experience: commercialExperience,
  },
  'bpm-llp': {
    focus: 'Business advisory & practical technology',
    headline: ['Understand the stage.', 'Build the useful support.'],
    introduction: 'For BPM, I selected work spanning financial analysis, operating plans, and software tools. Running VOID and researching early-stage businesses gives me a practical interest in matching a recommendation to the business’s actual question and resources.',
    priorities: [priority('Business context', 'Identify the decision, constraints, and resources behind the request.'), priority('Financial analysis', 'Make assumptions and definitions visible in the operating model.'), priority('Practical tools', 'Turn research and recurring tasks into usable workflows.')],
    work: ['markets', 'atlas', 'internshipdeadlines'],
    reading: [reading.homeServices, reading.findings],
    experience: ['VOID Agency', 'Jon Brumley Texas Venture Labs', 'Chegg, Inc.'],
  },
}

/** New registered companies receive a complete page without invented industry facts. */
export function recruiterCompanyProfile(slug: string, name: string): RecruiterCompanyProfile {
  if (Object.hasOwn(recruiterCompanyProfiles, slug)) return recruiterCompanyProfiles[slug]
  return {
    focus: 'Product, commercial research & systems',
    headline: ['Understand the question.', 'Build something useful.'],
    introduction: `I selected this work for the team at ${name}: products I’ve built, commercial questions I’ve researched, and systems that keep their evidence inspectable. My experience spans Chegg, Sapien, and independent work through VOID.`,
    priorities: [priority('Product thinking', 'Start with the user’s task and define the useful end state.'), priority('Commercial research', 'Connect customer needs, pricing, and financial assumptions.'), priority('Practical systems', 'Build usable tools and keep the sources behind their conclusions.')],
    work: ['internshipdeadlines', 'sapien', 'atlas'],
    reading: [reading.atlas, reading.managers],
    experience: ['Chegg, Inc.', 'Sapien', 'VOID Agency'],
  }
}
