/** Real CC0 VSCO 2 CE samples; generated by tools/prepare-about-audio.mjs --solo. */
export const bassSoloSamples = [
  {
    "file": "arco-G-sharp3.wav",
    "articulation": "arco",
    "midi": 56,
    "frequency": 207.45327
  },
  {
    "file": "arco-B3.wav",
    "articulation": "arco",
    "midi": 59,
    "frequency": 246.22311
  }
] as const
