/** Real CC0 VSCO 2 CE samples; generated by tools/prepare-about-audio.mjs. */
export const bassSamples = [
  {
    "file": "pizzicato-E1.wav",
    "articulation": "pizzicato",
    "midi": 28,
    "frequency": 41.17152
  },
  {
    "file": "pizzicato-G1.wav",
    "articulation": "pizzicato",
    "midi": 31,
    "frequency": 48.97902
  },
  {
    "file": "pizzicato-C2.wav",
    "articulation": "pizzicato",
    "midi": 36,
    "frequency": 65.37713
  },
  {
    "file": "pizzicato-E2.wav",
    "articulation": "pizzicato",
    "midi": 40,
    "frequency": 82.38126
  },
  {
    "file": "pizzicato-A2.wav",
    "articulation": "pizzicato",
    "midi": 45,
    "frequency": 110.9011
  },
  {
    "file": "pizzicato-C-sharp3.wav",
    "articulation": "pizzicato",
    "midi": 49,
    "frequency": 138.5819
  },
  {
    "file": "pizzicato-E3.wav",
    "articulation": "pizzicato",
    "midi": 52,
    "frequency": 164.89595
  },
  {
    "file": "arco-E1.wav",
    "articulation": "arco",
    "midi": 28,
    "frequency": 41.20216
  },
  {
    "file": "arco-G1.wav",
    "articulation": "arco",
    "midi": 31,
    "frequency": 49.01056
  },
  {
    "file": "arco-C2.wav",
    "articulation": "arco",
    "midi": 36,
    "frequency": 65.40393
  },
  {
    "file": "arco-E2.wav",
    "articulation": "arco",
    "midi": 40,
    "frequency": 82.36545
  },
  {
    "file": "arco-A2.wav",
    "articulation": "arco",
    "midi": 45,
    "frequency": 109.8991
  },
  {
    "file": "arco-C-sharp3.wav",
    "articulation": "arco",
    "midi": 49,
    "frequency": 138.56083
  },
  {
    "file": "arco-E3.wav",
    "articulation": "arco",
    "midi": 52,
    "frequency": 164.8237
  }
] as const
