export const additionalWorkProofCards = [
  {
    id: 'internshipdeadlines',
    eyebrow: 'Product',
    title: 'InternshipDeadlines',
    href: 'https://internshipdeadlines.com/',
    problem: 'Internship recruiting information is fragmented across employer sites, applicant-tracking systems, changing deadlines, and inconsistent job metadata.',
    role: 'Founder and product owner across product direction, data systems, content operations, and growth infrastructure.',
    built: 'A student-facing internship discovery product backed by structured ingestion, canonical job handling, deadline-aware content, search/discovery surfaces, and an operating SEO and publication system.',
    constraints: 'Employer data changes continuously. Source freshness, duplicate identity, uncertain deadlines, and publication eligibility have to remain explicit rather than being silently normalized away.',
    status: 'Live product under active expansion and continuous data/content operations.',
    statusLabel: 'Live / operating',
    projectLabel: 'Open InternshipDeadlines',
    evidenceLabel: 'Inspect the live product',
    evidenceHref: 'https://internshipdeadlines.com/',
    notPublic: 'Production credentials, private analytics, provider configuration, unpublished source evidence, and internal operating queues.',
  },
  {
    id: 'project-delta',
    eyebrow: 'Graphics engineering',
    title: 'Project Delta',
    href: 'https://sulayman-bowles.tech/',
    problem: 'Real-time visual systems are easy to make impressive and hard to make reproducible: shader behavior, object-space coordinates, browser performance, and visual regressions all move together.',
    role: 'Builder across shader architecture, React Three Fiber integration, evaluation design, performance instrumentation, and technical publication.',
    built: 'A reusable Three.js dithering post-processing system with ordered and procedural patterns, object-space anchors, palette and tone controls, plus browser load testing and deterministic visual-proof harnesses.',
    constraints: 'GPU timing and pixel output are environment-dependent. Unsupported timer queries and machine-specific baselines are recorded as measurement gaps rather than converted into performance claims.',
    status: 'Implemented engineering system with a public technical proof layer and continuing shader/evaluation work.',
    statusLabel: 'Implemented / public proof',
    projectLabel: 'Open Project Delta',
    evidenceLabel: 'Read the shader testing record',
    evidenceHref: 'https://sulayman-bowles.tech/articles/testing-a-dithering-shader',
    notPublic: 'Private repository history, local-only test artifacts, machine state, and unpublished experiments.',
  },
  {
    id: 'payrollpro',
    eyebrow: 'Hackathon / crypto',
    title: 'PayrollPro — OnionDAO',
    href: 'https://sulayman-bowles.tech/competitions/oniondao-payrollpro',
    problem: 'Crypto-native payroll needs privacy and treasury controls without turning every salary payment and operating balance into public information.',
    role: 'Team lead for a three-person hackathon team; product framing, system direction, and integration across the payroll and treasury-control concept.',
    built: 'A Solana payroll prototype combining confidential-transfer patterns, multisig treasury controls, payroll flows, and treasury-risk logic.',
    constraints: 'Hackathon prototype scope; not represented as audited payroll infrastructure, production custody software, or a deployed financial service.',
    status: '1st Place, OnionDAO Hackathon, June 2025.',
    statusLabel: '1st place',
    projectLabel: 'Read the project dossier',
    evidenceLabel: 'Open the public source archive',
    evidenceHref: 'https://github.com/SulaymanB2024/OnionDAO-Project',
    notPublic: 'Any private team materials, credentials, wallet secrets, and claims beyond the documented prototype and competition result.',
  },
  {
    id: 'no-limit-artemis',
    eyebrow: 'Investment research',
    title: 'No Limit x Artemis — MetaDAO Thesis',
    href: 'https://sulayman-bowles.tech/competitions/no-limit-artemis-researchathon',
    problem: 'Token analysis becomes shallow when governance, treasury control, ownership, market structure, incentives, valuation inputs, and execution risk are treated as separate topics.',
    role: 'Investment research author across thesis construction, public-data analysis, valuation framing, market structure, risk assessment, and execution planning.',
    built: 'A MetaDAO-focused digital-asset investment thesis treating token design as capital formation and ownership infrastructure, with explicit decision-market, treasury, valuation, and execution-risk analysis.',
    constraints: 'Public-source research with time-sensitive token and market inputs; the published dossier separates authored analysis from external verification.',
    status: 'Crypto Investment Research Prize Winner at the No Limit Holdings x Artemis Researchathon, Penn Blockchain Conference, March 2026.',
    statusLabel: 'Prize winner',
    projectLabel: 'Read the research dossier',
    evidenceLabel: 'Inspect the public thesis record',
    evidenceHref: 'https://sulayman-bowles.tech/competitions/no-limit-artemis-researchathon',
    notPublic: 'Private judging materials, non-public diligence, current trading positions, and any investment recommendation beyond the dated research artifact.',
  },
  {
    id: 'mandatearc',
    eyebrow: 'Enterprise AI product',
    title: 'MandateArc',
    href: '/work#mandatearc',
    problem: 'Enterprise workflow data can be commercially valuable for AI, but raw-data intake creates rights, privacy, diligence, and custody problems before a buyer and owner even agree on the mandate.',
    role: 'Product and systems builder across information architecture, qualification logic, buyer/owner workflows, evidence boundaries, and release verification.',
    built: 'An SEO-first enterprise workflow-data origination product with separate owner and buyer paths, metadata-only qualification, evidence maps, RFP and diligence tools, licensing/valuation guidance, industry routes, and a local operating control room.',
    constraints: 'The product deliberately excludes raw records, credentials, customer information, employee messages, recordings, contracts, and source code from intake. Deployment and commercial activation are separate proof gates.',
    status: 'Substantial private product build; public portfolio record added without exposing private research or operating details.',
    statusLabel: 'Private build',
    projectLabel: 'Read the portfolio record',
    evidenceLabel: null,
    evidenceHref: null,
    notPublic: 'Private Drive research, operator state, deployment details not independently verified for publication, buyer/owner outreach, and confidential workflow-data opportunities.',
  },
  {
    id: 'jane-street-puzzle',
    eyebrow: 'Constraint solving',
    title: 'Jane Street July 2026 Puzzle Solver',
    href: 'https://sulayman-bowles.tech/competitions/jane-street-puzzle-leaderboard',
    problem: 'The puzzle required schedule interpretation, 3D knight-move legality, regional tower placement, score arithmetic, and a final stopping condition to agree in one reproducible solution.',
    role: 'Solver author; exact-search design, independent verification, artifact generation, and publication.',
    built: 'A standard-library Python exact search plus a separate verifier, path table, clue audit, unvisited-neighbor calculations, and machine-readable solution artifacts.',
    constraints: 'The public portfolio record keeps self-authored solver evidence distinct from official Jane Street confirmation and preserves gaps where immutable external evidence is unavailable.',
    status: 'Published July 2026 solver record; leaderboard attribution is presented with its evidence boundary.',
    statusLabel: 'Published solver',
    projectLabel: 'Read the solver dossier',
    evidenceLabel: 'Inspect the public solver record',
    evidenceHref: 'https://sulayman-bowles.tech/competitions/jane-street-puzzle-leaderboard',
    notPublic: 'Private repository history and any result claim that cannot be supported by the published evidence boundary.',
  },
  {
    id: 'internship-aggregator-engine',
    eyebrow: 'Data infrastructure',
    title: 'Internship Aggregator Engine',
    href: '/work#internship-aggregator-engine',
    problem: 'Aggregating internship listings is an evidence and identity problem before it is a scraping problem: partial scans, duplicates, closures, reopenings, and source changes can silently corrupt a directory.',
    role: 'System architect and builder across ingestion, provenance, canonical identity, scheduling, publication boundaries, API design, and verification.',
    built: 'An evidence-first modular monolith with Greenhouse, Lever, Ashby, and JSON-LD adapters; immutable observation snapshots; field provenance; reversible identity decisions; durable scheduling; transactional projections; and a searchable API/server-rendered surface.',
    constraints: 'Live acquisition is policy-gated and disabled by default. Partial pagination cannot create false closure or reopen events, and publication responses exclude acquisition evidence and direct source destinations.',
    status: 'Private engineering system with deterministic offline E2E coverage and bounded production-shaped worker controls.',
    statusLabel: 'Implemented / private',
    projectLabel: 'Read the portfolio record',
    evidenceLabel: null,
    evidenceHref: null,
    notPublic: 'Private repository source, source-policy evidence, worker configuration, production credentials, and acquisition records not approved for publication.',
  },
  {
    id: '1-800-operator',
    eyebrow: 'AI systems',
    title: '1-800-Operator',
    href: '/work#1-800-operator',
    problem: 'Short-form trend and resale-content research becomes unreliable when examples, model analysis, provider calls, creative generation, and publishing are blended into one opaque agent loop.',
    role: 'Builder of the operating harness, evidence model, provider boundaries, evaluation surfaces, and Codex-facing autonomy controls.',
    built: 'A private marketing-intelligence workspace with SQLite/FTS trend evidence, grounded content briefs, creative-job artifacts, explicit provider capability gates, reproducibility manifests, cost caps, and Codex run/audit surfaces.',
    constraints: 'The repository explicitly separates observed examples, derived strategy, paid-provider analysis, generated assets, and publishing. External calls and posting remain gated rather than assumed available.',
    status: 'Private internal system under active development; only a sanitized system-level record is public here.',
    statusLabel: 'Private / active',
    projectLabel: 'Read the portfolio record',
    evidenceLabel: null,
    evidenceHref: null,
    notPublic: 'Implementation details, provider configuration, credentials, internal evidence artifacts, operating procedures, and unpublished campaign data.',
  },
] as const;
