import type { ContentClusterId } from './contentClusters';

export type ProjectIndexItem = {
  id: string;
  title: string;
  clusterId: ContentClusterId;
  ownershipLabel: string;
  statusLabel: string;
  visibilityLabel: string;
  summary: string;
  evidenceBoundary: string;
  href?: string;
  linkLabel?: string;
  relatedPaths: readonly string[];
};

export const PROJECT_INDEX: readonly ProjectIndexItem[] = [
  {
    id: 'atlas-engine',
    title: 'Atlas SEO Audit Engine',
    clusterId: 'search-crawl-systems',
    ownershipLabel: 'Builder / owner',
    statusLabel: 'Working system',
    visibilityLabel: 'Public product page and code',
    summary: 'Evidence-first crawl and audit software with deterministic issue logic, inspectable source records, and structured exports.',
    evidenceBoundary: 'The public sample proves a bounded open-corpus run; it does not claim universal crawl coverage or client outcomes.',
    href: '/atlas',
    linkLabel: 'Open Atlas',
    relatedPaths: ['/atlas/sample-crawl', '/research/technical-seo'],
  },
  {
    id: 'void-agency',
    title: 'Void Agency',
    clusterId: 'technical-seo',
    ownershipLabel: 'Founder / operator',
    statusLabel: 'Active practice',
    visibilityLabel: 'Public site',
    summary: 'A technical SEO practice organized around crawlability, indexation, structured content, analytics, implementation, and rerun checks.',
    evidenceBoundary: 'The public method documents scope and operating standards; it is not a substitute for private client evidence.',
    href: 'https://www.void-agency.com/',
    linkLabel: 'Visit Void Agency',
    relatedPaths: ['/method', '/contact'],
  },
  {
    id: 'content-spy-helios',
    title: 'Content Spy / Helios',
    clusterId: 'search-crawl-systems',
    ownershipLabel: 'Builder',
    statusLabel: 'Implementation harness',
    visibilityLabel: 'Private working repository',
    summary: 'A local-first competitor-intelligence and content-research system designed around governed web capture and comparable evidence.',
    evidenceBoundary: 'The repository is an implementation harness, not a finished hosted SaaS product; production data services are not claimed.',
    relatedPaths: ['/research/search-systems'],
  },
  {
    id: 'portfolio-site',
    title: 'Portfolio Site',
    clusterId: 'technical-seo',
    ownershipLabel: 'Designer / developer',
    statusLabel: 'Live and maintained',
    visibilityLabel: 'Public site and code',
    summary: 'The canonical identity, research, project, static-rendering, structured-data, and analytics surface for sulayman-bowles.dev.',
    evidenceBoundary: 'The repository and live routes show implementation; search exposure and citations remain measured outcomes, not design claims.',
    href: 'https://github.com/SulaymanB2024/Portfolio_Site',
    linkLabel: 'View source',
    relatedPaths: ['/research', '/work'],
  },
  {
    id: 'technical-ledger',
    title: 'Technical Ledger',
    clusterId: 'search-crawl-systems',
    ownershipLabel: 'Builder / publisher',
    statusLabel: 'Live proof layer',
    visibilityLabel: 'Public site',
    summary: 'A separate public ledger for project artifacts, datasets, benchmarks, tags, and bounded retrieval over published evidence.',
    evidenceBoundary: 'The ledger expands artifact access without replacing this site as the canonical identity source.',
    href: 'https://sulayman-bowles.tech/',
    linkLabel: 'Open the ledger',
    relatedPaths: ['/research/search-systems'],
  },
  {
    id: 'austin-crawlability-pilot',
    title: 'Austin Crawlability Pilot',
    clusterId: 'technical-seo',
    ownershipLabel: 'Researcher / builder',
    statusLabel: 'Published bounded study',
    visibilityLabel: 'Public page and data',
    summary: 'A dated 12-site public-homepage study with crawlability observations, a summary file, and a downloadable source table.',
    evidenceBoundary: 'The sample is a crawlability baseline, not a ranking, traffic, revenue, or whole-site health claim.',
    href: '/austin-technical-seo',
    linkLabel: 'Inspect the pilot',
    relatedPaths: ['/research/technical-seo'],
  },
  {
    id: 'king-maker',
    title: 'KING Maker',
    clusterId: 'ai-agent-systems',
    ownershipLabel: 'System architect / builder',
    statusLabel: 'Evidence-first MVP',
    visibilityLabel: 'Private working repository',
    summary: 'A clean-room internship aggregation engine with immutable observations, field provenance, canonical records, and publication eligibility gates.',
    evidenceBoundary: 'Candidate records, provider claims, and synthetic fixtures are not counted as accepted live coverage.',
    relatedPaths: ['/research/ai-systems'],
  },
  {
    id: 'queen-maker',
    title: 'QUEEN Maker',
    clusterId: 'ai-agent-systems',
    ownershipLabel: 'System architect / builder',
    statusLabel: 'Source-strategy bootstrap',
    visibilityLabel: 'Private working repository',
    summary: 'A separate job-data architecture for lawful acquisition, canonical deduplication, lineage, acceptance controls, and sealed snapshots.',
    evidenceBoundary: 'It is a source-only bootstrap: no five-million-job coverage, live acquisition, or cloud deployment is claimed.',
    relatedPaths: ['/research/ai-systems'],
  },
  {
    id: 'viralbench-codex',
    title: 'ViralBench + Codex Agent Harness',
    clusterId: 'ai-agent-systems',
    ownershipLabel: 'Evaluation-system designer',
    statusLabel: 'Published architecture',
    visibilityLabel: 'Public research article',
    summary: 'A code-level design for traces, offline replay, controlled trials, permissions, and bounded engineering changes around a marketing agent.',
    evidenceBoundary: 'The article presents an evaluation architecture, not a deployed autonomous marketing service or performance guarantee.',
    href: '/viralbench-codex-agent-harness',
    linkLabel: 'Read the design',
    relatedPaths: ['/research/ai-systems'],
  },
  {
    id: 'linedown-desk',
    title: 'LineDown Desk',
    clusterId: 'ai-agent-systems',
    ownershipLabel: 'Product architect / builder',
    statusLabel: 'Offline review-first prototype',
    visibilityLabel: 'Private working repository',
    summary: 'A maintenance-materials intake agent with typed extraction, evidence spans, deterministic policy checks, exception routing, replay, and fake ERP export packets.',
    evidenceBoundary: 'The working demo uses synthetic fixtures and has no live mailbox, customer send, OCR vendor, production database, or ERP write path.',
    relatedPaths: ['/research/ai-systems'],
  },
  {
    id: 'project-delta',
    title: 'Project Delta / D-Shaders',
    clusterId: 'ai-agent-systems',
    ownershipLabel: 'Creative developer',
    statusLabel: 'Interactive prototype',
    visibilityLabel: 'Private source; restricted preview',
    summary: 'A reusable real-time dithering and post-processing system for Three.js scenes, demonstrated through an interactive helmet experience.',
    evidenceBoundary: 'The hosted preview currently requires authorization; no public demo or packaged production graphics platform is claimed.',
    relatedPaths: ['/work'],
  },
  {
    id: 'applypilot-contribution',
    title: 'ApplyPilot Systems Contribution',
    clusterId: 'ai-agent-systems',
    ownershipLabel: 'Contributor / systems work',
    statusLabel: 'Contribution workspace',
    visibilityLabel: 'Attribution retained',
    summary: 'Automation and systems work performed in a workspace derived from the open-source ApplyPilot project.',
    evidenceBoundary: 'ApplyPilot originated with Pickle-Pixel; this entry claims contribution work, not authorship of the upstream product.',
    relatedPaths: ['/research/ai-systems'],
  },
  {
    id: 'dropkit-sui',
    title: 'DropKit on Sui',
    clusterId: 'ai-agent-systems',
    ownershipLabel: 'Prototype builder',
    statusLabel: 'Testnet MVP scaffold',
    visibilityLabel: 'Public code',
    summary: 'A ticket resale prototype using Sui Kiosk, Transfer Policy, and programmable transactions so artist royalties remain part of resale execution.',
    evidenceBoundary: 'The repository describes a testnet milestone plan; later wallet, sponsorship, asset, and frontend milestones are not presented as shipped.',
    href: 'https://github.com/SulaymanB2024/SUI_CalHacks',
    linkLabel: 'View repository',
    relatedPaths: ['/research/ai-systems'],
  },
  {
    id: 'privacy-token-prototypes',
    title: 'pUSD and OnionUSD-P',
    clusterId: 'ai-agent-systems',
    ownershipLabel: 'Prototype builder / adapter',
    statusLabel: 'Local blockchain prototypes',
    visibilityLabel: 'Private working repositories',
    summary: 'Solana Token-2022 experiments spanning confidential transfers, reserve logic, payroll batches, allow-listed redemption, and feature-gated yield concepts.',
    evidenceBoundary: 'These are code and test prototypes; no production mint, audited reserve, live collateral, or mainnet deployment is claimed.',
    relatedPaths: ['/research/ai-systems'],
  },
  {
    id: 'challenge-solver',
    title: 'On-Chain Challenge Solver',
    clusterId: 'ai-agent-systems',
    ownershipLabel: 'Developer',
    statusLabel: 'Archived testnet tool',
    visibilityLabel: 'Unlinked pending release review',
    summary: 'A Base Sepolia contract-challenge toolkit for transaction inspection, answer signing, winner verification, and reward-claim experiments.',
    evidenceBoundary: 'The archival workspace contains live-action scripts and is not presented as safe to run; credential and release hygiene require review before public linking.',
    relatedPaths: ['/research/ai-systems'],
  },
  {
    id: 'coin-app-research',
    title: 'Coin App Research Archive',
    clusterId: 'markets-models',
    ownershipLabel: 'Researcher / developer',
    statusLabel: 'Public research repository',
    visibilityLabel: 'Public code and notes',
    summary: 'A cryptocurrency research archive for comparing product, protocol, and market questions through inspectable notes and code.',
    evidenceBoundary: 'The repository is research material, not a production trading product or investment recommendation.',
    href: 'https://github.com/SulaymanB2024/coin-app',
    linkLabel: 'View repository',
    relatedPaths: ['/markets'],
  },
  {
    id: 'texas-toll-road-research',
    title: 'Texas Toll-Road Ownership Research',
    clusterId: 'markets-models',
    ownershipLabel: 'Researcher / model builder',
    statusLabel: 'Published source-led study',
    visibilityLabel: 'Public article and data',
    summary: 'An ownership, concession, operator, debt, and finite-life cash-flow map for major Texas toll-road systems.',
    evidenceBoundary: 'Scenario values are analyst screening estimates, not bids, appraisals, fairness opinions, or current security quotations.',
    href: '/markets/who-owns-texas-toll-roads',
    linkLabel: 'Read the study',
    relatedPaths: ['/markets'],
  },
  {
    id: 'race-the-case',
    title: 'Race the Case Decision Model',
    clusterId: 'markets-models',
    ownershipLabel: 'Model builder / competitor',
    statusLabel: 'Completed competition system',
    visibilityLabel: 'Public code',
    summary: 'A Python financial-report generator and decision framework for scenario analysis, operating assumptions, and competition-ready outputs.',
    evidenceBoundary: 'Outputs are competition analysis, not audited financial statements or investment advice.',
    href: 'https://github.com/SulaymanB2024/5-Race-the-Case-Competition',
    linkLabel: 'View repository',
    relatedPaths: ['/markets'],
  },
  {
    id: 'datahack-wind',
    title: 'DataHack Wind Forecasting',
    clusterId: 'markets-models',
    ownershipLabel: 'Data scientist / competitor',
    statusLabel: 'Completed modeling project',
    visibilityLabel: 'Public code',
    summary: 'A wind-speed forecasting and event-modeling project using time-series, tree-based, cross-validation, and ensemble methods.',
    evidenceBoundary: 'Repository results describe the competition dataset and evaluation setup, not a live operational forecast.',
    href: 'https://github.com/SulaymanB2024/DataHack',
    linkLabel: 'View repository',
    relatedPaths: ['/markets'],
  },
  {
    id: 'imc-prosperity',
    title: 'IMC Prosperity Trading Systems',
    clusterId: 'markets-models',
    ownershipLabel: 'Strategy developer / competitor',
    statusLabel: 'Competition research family',
    visibilityLabel: 'Public code and local backtests',
    summary: 'Trading-bot data pipelines, feature experiments, strategy reports, and backtesting work built around the IMC Prosperity competition.',
    evidenceBoundary: 'Backtests and competition results are bounded to their datasets and rules; no live trading performance is claimed.',
    href: 'https://github.com/SulaymanB2024/IMC_BOT',
    linkLabel: 'View public code',
    relatedPaths: ['/markets'],
  },
  {
    id: 'sezzle-model',
    title: 'Sezzle Fundamental Model',
    clusterId: 'markets-models',
    ownershipLabel: 'Researcher / model builder',
    statusLabel: 'Completed model',
    visibilityLabel: 'Public code',
    summary: 'A fundamental-analysis pipeline spanning ETL, credit-loss assumptions, operating drivers, and a valuation lattice.',
    evidenceBoundary: 'The model is an educational research artifact, not a current price target or investment recommendation.',
    href: 'https://github.com/SulaymanB2024/sezzle-fundamental-model',
    linkLabel: 'View repository',
    relatedPaths: ['/markets'],
  },
  {
    id: 'coal-forecasting',
    title: 'Global Coal Price Forecasting',
    clusterId: 'markets-models',
    ownershipLabel: 'Researcher / model builder',
    statusLabel: 'Completed forecasting study',
    visibilityLabel: 'Public code',
    summary: 'An ARIMAX-based global coal-price forecasting project with explicit data preparation, drivers, and model outputs.',
    evidenceBoundary: 'The study was finalized in April 2025 and should not be read as a current commodity forecast.',
    href: 'https://github.com/SulaymanB2024/UTexas_Coal',
    linkLabel: 'View repository',
    relatedPaths: ['/markets'],
  },
  {
    id: 'energy-trading',
    title: 'UT Austin Energy Trading Research',
    clusterId: 'markets-models',
    ownershipLabel: 'Researcher / analyst',
    statusLabel: 'Completed research project',
    visibilityLabel: 'Public code',
    summary: 'WTI spot-price analysis and energy-market research using public EIA data and reproducible analytical work.',
    evidenceBoundary: 'The repository is a historical research exercise, not a live commodity-trading signal.',
    href: 'https://github.com/SulaymanB2024/UTexas_EnergyTrading',
    linkLabel: 'View repository',
    relatedPaths: ['/markets'],
  },
  {
    id: 'solana-balance-engine',
    title: 'Solana Balance History Engine',
    clusterId: 'markets-models',
    ownershipLabel: 'Developer',
    statusLabel: 'Working data utility',
    visibilityLabel: 'Public code',
    summary: 'A native-SOL balance reconstruction utility that derives exact wallet balances over time from Helius-backed transaction history.',
    evidenceBoundary: 'The tool reconstructs balance history for supplied data; it is not a portfolio tracker, custody service, or performance claim.',
    href: 'https://github.com/SulaymanB2024/sturdy-lamp',
    linkLabel: 'View repository',
    relatedPaths: ['/markets'],
  },
  {
    id: 'funding-research-studio',
    title: 'Funding Research Studio',
    clusterId: 'markets-models',
    ownershipLabel: 'Researcher / tool builder',
    statusLabel: 'Local research system',
    visibilityLabel: 'Private working repository',
    summary: 'A research workspace for perpetual funding, liquidity, and cross-venue comparisons across decentralized and centralized exchanges.',
    evidenceBoundary: 'The workspace supports research and screening; it is not an autonomous arbitrage executor or verified profit record.',
    relatedPaths: ['/markets'],
  },
  {
    id: 'portfolio-design-archive',
    title: 'Portfolio and Web Design Archive',
    clusterId: 'technical-seo',
    ownershipLabel: 'Designer / developer',
    statusLabel: 'Archived project family',
    visibilityLabel: 'Public and private historical repositories',
    summary: 'Earlier portfolio, investment-site, venture-site, and visual-interface iterations consolidated as one design lineage.',
    evidenceBoundary: 'Duplicate clones and superseded site iterations are grouped here rather than counted as separate current products.',
    relatedPaths: ['/work'],
  },
] as const;

export const PROJECT_FAMILY_COUNT = PROJECT_INDEX.length;

export function getProjectsForCluster(clusterId: ContentClusterId) {
  return PROJECT_INDEX.filter((project) => project.clusterId === clusterId);
}

export function isExternalProjectHref(href: string | undefined) {
  return Boolean(href?.startsWith('http'));
}
