import type { ResearchArticle } from './articleModels';

export const RESEARCH_ARTICLES: ResearchArticle[] = [
  {
    kind: 'research',
    cluster: 'ai-crawlers',
    slug: 'ai-search-crawler-policy',
    number: '01',
    category: 'CRAWLER POLICY',
    title: 'AI Crawler Robots.txt Guide: GPTBot, OAI-SearchBot, ClaudeBot and PerplexityBot',
    seoTitle: 'AI Crawler Robots.txt Guide: GPTBot, OAI-SearchBot, ClaudeBot and PerplexityBot',
    subtitle: 'A role-by-role guide to AI search, training, and user-triggered agents, with deployable robots.txt policies and log-verification steps.',
    seoDescription:
      'Compare OpenAI, Anthropic, and Perplexity crawler user agents, then copy robots.txt policies for allowing AI search, blocking training, or blocking named AI agents.',
    image: '/og-default.png',
    date: '2026.06.19',
    dateModified: '2026.07.14',
    lastVerified: '2026.07.14',
    readTime: '14 MIN',
    author: 'SULAYMAN BOWLES',
    thesis:
      'Treat search crawlers, training crawlers, and user-triggered fetchers as separate policy choices, then verify observed traffic with server logs and provider-published IP ranges.',
    evidenceBoundary:
      'This guide documents published crawler controls as verified on July 14, 2026. A robots.txt rule expresses policy; it does not secure private content, authenticate a bot, or prove indexing, ranking, training exclusion, or answer-system citation.',
    metrics: [
      { label: 'Agents compared', value: '8 USER AGENTS' },
      { label: 'Policies', value: '2 COPY-READY' },
      { label: 'Last verified', value: '2026.07.14' },
    ],
    sources: [
      { label: 'OpenAI crawler documentation', href: 'https://developers.openai.com/api/docs/bots', lastVerified: '2026.07.14' },
      {
        label: 'Anthropic crawler guidance',
        href: 'https://support.claude.com/en/articles/8896518-does-anthropic-crawl-data-from-the-web-and-how-can-site-owners-block-the-crawler',
        lastVerified: '2026.07.14',
      },
      { label: 'Perplexity crawler documentation', href: 'https://docs.perplexity.ai/docs/resources/perplexity-crawlers', lastVerified: '2026.07.14' },
      { label: 'Google robots.txt introduction and limitations', href: 'https://developers.google.com/search/docs/crawling-indexing/robots/intro', lastVerified: '2026.07.14' },
      { label: 'OpenAI OAI-SearchBot IP ranges', href: 'https://openai.com/searchbot.json', lastVerified: '2026.07.14' },
      { label: 'OpenAI GPTBot IP ranges', href: 'https://openai.com/gptbot.json', lastVerified: '2026.07.14' },
      { label: 'OpenAI ChatGPT-User IP ranges', href: 'https://openai.com/chatgpt-user.json', lastVerified: '2026.07.14' },
      { label: 'Anthropic bot IP ranges', href: 'https://claude.com/crawling/bots.json', lastVerified: '2026.07.14' },
      { label: 'PerplexityBot IP ranges', href: 'https://www.perplexity.ai/perplexitybot.json', lastVerified: '2026.07.14' },
      { label: 'Perplexity-User IP ranges', href: 'https://www.perplexity.ai/perplexity-user.json', lastVerified: '2026.07.14' },
    ],
    content: [
      'AI crawler policy is not one yes-or-no switch. OpenAI, Anthropic, and Perplexity publish different agents for search discovery, model-development crawling, and fetches initiated by a user. A useful robots.txt file starts by deciding what each role may access instead of treating every AI-related request as equivalent.',
      'The configurations below are policy templates, not security controls. Publish them at the root of every host and subdomain they are meant to govern, test the live response, then inspect access logs. Keep confidential or regulated material behind authentication because a robots.txt file is public and voluntary.',
    ],
    sections: [
      {
        id: 'crawler-types',
        title: 'Search crawler versus training crawler versus user-triggered crawler',
        paragraphs: [
          'A search crawler builds or improves an index used to retrieve and cite web pages in an answer product. A training crawler gathers public content that may contribute to future foundation-model development. A user-triggered crawler or fetcher visits a URL because a person asked a product to retrieve it at that moment.',
          'Those roles have different consequences. Blocking a search crawler can reduce eligibility for that provider\'s search results. Blocking a training crawler expresses an opt-out from future training collection without necessarily blocking search. Blocking a user-triggered fetcher can prevent a product from opening a page on a user\'s behalf, but robots.txt behavior is provider-specific.',
        ],
        bullets: [
          'Search: OAI-SearchBot, Claude-SearchBot, and PerplexityBot.',
          'Training or model development: GPTBot and ClaudeBot.',
          'User-triggered retrieval: ChatGPT-User, Claude-User, and Perplexity-User.',
        ],
      },
      {
        id: 'crawler-comparison',
        title: 'AI crawler comparison table',
        paragraphs: [
          'Use the exact case-sensitive product tokens below in robots.txt. Version numbers in full HTTP User-Agent strings can change, so policy should target the stable token rather than a copied versioned string.',
        ],
        table: {
          caption: 'Published AI crawler roles and robots.txt behavior, last verified July 14, 2026',
          columns: ['Provider', 'Exact user-agent', 'Role', 'robots.txt behavior', 'Operational note', 'Last verified'],
          rows: [
            ['OpenAI', 'OAI-SearchBot', 'Search crawler', 'Supported', 'Controls inclusion in ChatGPT search answers; navigational links may still appear.', '2026-07-14'],
            ['OpenAI', 'GPTBot', 'Training crawler', 'Supported', 'Disallowing signals that crawled content should not be used to train generative AI foundation models.', '2026-07-14'],
            ['OpenAI', 'ChatGPT-User', 'User-triggered fetcher', 'May not apply', 'Not used for automatic crawling or Search inclusion; requests are initiated by a user.', '2026-07-14'],
            ['Anthropic', 'Claude-SearchBot', 'Search crawler', 'Honored', 'Supports search quality and indexing for Claude search responses.', '2026-07-14'],
            ['Anthropic', 'ClaudeBot', 'Training crawler', 'Honored', 'Collects public content that could contribute to model training.', '2026-07-14'],
            ['Anthropic', 'Claude-User', 'User-triggered fetcher', 'Honored', 'Retrieves content in response to a Claude user request.', '2026-07-14'],
            ['Perplexity', 'PerplexityBot', 'Search crawler', 'Supported', 'Surfaces and links websites in Perplexity search; not used for foundation-model training.', '2026-07-14'],
            ['Perplexity', 'Perplexity-User', 'User-triggered fetcher', 'Generally ignored', 'Perplexity says this user-requested fetcher generally ignores robots.txt.', '2026-07-14'],
          ],
        },
      },
      {
        id: 'robots-configurations',
        title: 'Copy-and-paste robots.txt configurations',
        paragraphs: [
          'These examples cover the named agents in the comparison table. They are not an exhaustive registry of every AI-related crawler on the web. Preserve any existing rules for Googlebot, Bingbot, media crawlers, private paths, and your sitemap when merging a template into a live file.',
        ],
        codeExamples: [
          {
            title: 'Allow AI search but block training',
            description: 'Allows search-oriented and user-triggered access while blocking the two published training/model-development agents in this guide.',
            language: 'robots.txt',
            code: [
              'User-agent: OAI-SearchBot',
              'Allow: /',
              '',
              'User-agent: GPTBot',
              'Disallow: /',
              '',
              'User-agent: ChatGPT-User',
              'Allow: /',
              '',
              'User-agent: Claude-SearchBot',
              'Allow: /',
              '',
              'User-agent: ClaudeBot',
              'Disallow: /',
              '',
              'User-agent: Claude-User',
              'Allow: /',
              '',
              'User-agent: PerplexityBot',
              'Allow: /',
              '',
              'User-agent: Perplexity-User',
              'Allow: /',
              '',
              'Sitemap: https://example.com/sitemap.xml',
            ].join('\n'),
          },
          {
            title: 'Block all AI crawlers',
            description: 'Blocks every AI-related agent named in this guide. No static list can cover every crawler, ChatGPT-User rules may not apply, and Perplexity-User generally ignores robots.txt, so enforce sensitive-content controls at authentication or the server edge.',
            language: 'robots.txt',
            code: [
              'User-agent: OAI-SearchBot',
              'Disallow: /',
              '',
              'User-agent: GPTBot',
              'Disallow: /',
              '',
              'User-agent: ChatGPT-User',
              'Disallow: /',
              '',
              'User-agent: Claude-SearchBot',
              'Disallow: /',
              '',
              'User-agent: ClaudeBot',
              'Disallow: /',
              '',
              'User-agent: Claude-User',
              'Disallow: /',
              '',
              'User-agent: PerplexityBot',
              'Disallow: /',
              '',
              'User-agent: Perplexity-User',
              'Disallow: /',
            ].join('\n'),
          },
        ],
      },
      {
        id: 'robots-limitations',
        title: 'What robots.txt cannot accomplish',
        paragraphs: [
          'Robots.txt manages cooperative crawler access. It does not authenticate a requester, create a legal or technical access barrier, remove a URL from every index, or guarantee that previously collected material is deleted. A malicious client can copy a trusted User-Agent token, and compliant providers can interpret user-triggered requests differently from automatic crawling.',
          'Google also warns that a disallowed URL can still appear in search results when other pages link to it. Use authentication for private content, noindex for crawlable pages that should not appear in supporting search engines, and server or WAF rules when you need enforceable traffic controls. Do not block a page in robots.txt and expect a crawler to read a noindex directive on that blocked page.',
        ],
        bullets: [
          'It cannot keep secrets private or replace access control.',
          'It cannot prove a request came from the company named in its User-Agent.',
          'It cannot guarantee deindexing, ranking, citation, or model-training outcomes.',
          'It cannot retroactively govern content already fetched under an earlier policy.',
          'It cannot cover unknown or newly introduced agents unless the policy is reviewed and updated.',
        ],
      },
      {
        id: 'server-log-verification',
        title: 'Verify crawler behavior in server logs',
        paragraphs: [
          'Start with raw access logs rather than an analytics dashboard: many bot requests do not execute client-side analytics. Record the timestamp, request path, status, response bytes, source IP, host, and full User-Agent. The example below filters a standard NGINX access-log archive for the exact tokens in this guide.',
          'A matching User-Agent is only a claim. Compare the source IP with the provider\'s current published CIDR manifest, and retain the manifest retrieval time with your evidence. Do not hard-code today\'s ranges forever; providers update them. Then check whether requests to /robots.txt preceded content fetches, whether disallowed paths stopped receiving compliant automatic-crawler traffic after the provider\'s stated propagation window, and whether CDN or WAF rules changed the observed result.',
        ],
        bullets: [
          'Confirm /robots.txt returns 200 on every relevant host and contains the intended group.',
          'Filter logs by exact User-Agent token and review status codes, paths, rate, and timestamps.',
          'Validate the source IP against the linked OpenAI, Anthropic, or Perplexity JSON manifest.',
          'Separate automatic crawlers from user-triggered fetchers when interpreting compliance.',
          'Recheck after policy changes and keep a dated snapshot; absence of requests is not proof of blocking.',
        ],
        codeExamples: [
          {
            title: 'Find the named agents in NGINX logs',
            description: 'Adjust the log path for your server or CDN export. This reads current and rotated gzip logs without changing them.',
            language: 'shell',
            code: [
              "zgrep -hEi 'OAI-SearchBot|GPTBot|ChatGPT-User|ClaudeBot|Claude-SearchBot|Claude-User|PerplexityBot|Perplexity-User' /var/log/nginx/access.log*",
              '',
              "curl -sS -D - https://example.com/robots.txt -o /dev/null",
            ].join('\n'),
          },
        ],
      },
    ],
  },
  {
    kind: 'research',
    cluster: 'search-console',
    slug: 'technical-seo-public-data-infrastructure',
    number: '02',
    category: 'DATA INFRASTRUCTURE',
    title: 'Technical SEO as Public Data Infrastructure',
    seoTitle: 'Technical SEO as Data Infrastructure',
    subtitle: 'Why crawlability, structured data, and provenance matter for public discovery and finance-style research.',
    seoDescription:
      'Research note by Sulayman Bowles on technical SEO as public data infrastructure: crawl access, structured data, provenance, and SEC-style comparability.',
    image: '/og-default.png',
    date: '2026.06.19',
    dateModified: '2026.07.12',
    readTime: '09 MIN',
    author: 'SULAYMAN BOWLES',
    thesis:
      'Technical SEO is best understood as public-data infrastructure: access, stable identifiers, provenance, and consistent records before distribution.',
    evidenceBoundary:
      'The comparison to financial-data infrastructure is an analytical frame. A portfolio is not a regulated disclosure system, and infrastructure does not guarantee distribution.',
    metrics: [
      { label: 'Scope', value: 'SEO + DATA' },
      { label: 'Frame', value: 'INFRASTRUCTURE' },
      { label: 'Evidence standard', value: 'SOURCES FIRST' },
    ],
    sources: [
      { label: 'Google structured data introduction', href: 'https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data' },
      { label: 'Google helpful content guidance', href: 'https://developers.google.com/search/docs/fundamentals/creating-helpful-content' },
      { label: 'SEC EDGAR APIs', href: 'https://www.sec.gov/search-filings/edgar-application-programming-interfaces' },
      { label: 'SEC developer resources', href: 'https://www.sec.gov/about/developer-resources' },
      { label: 'Google sitemap overview', href: 'https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview' },
    ],
    content: [
      'Technical SEO is usually described as a marketing function, but the better frame is data infrastructure. Crawlers need access. Indexes need stable identifiers. Search systems need source clarity. Human readers need provenance. When those layers are missing, the site may still look polished, but it behaves like an unreliable dataset: hard to join, hard to verify, and easy to misread.',
      'Finance research gives a useful analogy. Public-market workflows depend on records that can be located, parsed, compared, and tied back to the issuer. SEC EDGAR APIs expose company submissions and extracted XBRL facts because serious analysis depends on structured public records. A personal site is not EDGAR, but the same quality instinct applies: if a public claim matters, it should have a stable URL, a date or context, a source link, and a consistent relationship to the rest of the public record.',
      'Google describes structured data as a standardized way to provide explicit clues about page meaning. That is not magic markup, and it is not a substitute for visible content. It is a way to make the page easier to classify when the page already says something useful. A ProfilePage schema should match the actual profile page. Article schema should describe the actual article.',
      'The public-data lens also changes how you think about old files. A stale PDF, duplicate subdomain, outdated bio, or orphaned project page is not only an aesthetic problem. It is a conflicting record. Search engines may discover it without understanding which version is current. Redirecting obsolete URLs, using one canonical host, and keeping internal links pointed at the preferred page are basic data hygiene steps.',
      'Google helpful-content guidance is useful here because it pulls the conversation away from mechanical SEO. The page should make clear who created the content, how the work was produced where that matters, and why the content exists. That is especially important for finance-adjacent writing. The reader should be able to see the assumptions, source base, and limits of the claim.',
      'The practical standard is not more pages. It is better public records. A technical SEO audit should ask whether the site has crawlable support pages, sourced claims, consistent authorship, structured data that matches visible content, and a sitemap that reflects the current public record.',
    ],
  },
  {
    kind: 'research',
    cluster: 'personal-seo',
    slug: 'canonical-identity-personal-seo',
    number: '03',
    category: 'ENTITY CONSISTENCY',
    title: 'Canonical Identity Beats More Content',
    seoTitle: 'Canonical Identity for Personal SEO',
    subtitle: 'A reconciliation checklist for profiles, stale PDFs, sameAs links, and public reference pages.',
    seoDescription:
      'Practical research note by Sulayman Bowles on identity cleanup, sameAs discipline, profile-page schema, stale resume PDFs, internal links, and external bio consistency.',
    image: '/og-default.png',
    date: '2026.06.19',
    dateModified: '2026.07.12',
    readTime: '07 MIN',
    author: 'SULAYMAN BOWLES',
    thesis:
      'A smaller set of current, connected records is more useful than publishing more disconnected versions of the same person.',
    evidenceBoundary:
      'External profiles can drift or block unauthenticated access. Only current, visibly matching profiles should be treated as identity evidence.',
    metrics: [
      { label: 'Scope', value: 'PERSON GRAPH' },
      { label: 'Priority', value: 'CANONICALS' },
      { label: 'Maintenance', value: 'ONGOING' },
    ],
    sources: [
      { label: 'Google canonicalization guide', href: 'https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls' },
      { label: 'Google ProfilePage structured data', href: 'https://developers.google.com/search/docs/appearance/structured-data/profile-page' },
      { label: 'Schema.org Person', href: 'https://schema.org/Person' },
      { label: 'Schema.org ProfilePage', href: 'https://schema.org/ProfilePage' },
      { label: 'Google structured data policies', href: 'https://developers.google.com/search/docs/appearance/structured-data/sd-policies' },
    ],
    content: [
      'The fastest way to weaken a personal SEO graph is to publish more disconnected versions of the same person. A portfolio homepage says one thing, an old resume PDF says another, GitHub says nothing, LinkedIn uses a different line, and a hackathon profile still points at an abandoned project. None of those pieces is necessarily wrong on its own. The problem is that crawlers and human reviewers have to decide which one is current.',
      'Canonical identity starts with one preferred host and one preferred profile thesis. Google describes redirects as one of the strongest canonicalization signals and recommends consistent canonical URLs across a site. For a personal site, that means the apex domain should resolve clearly, the www host should redirect, internal links should point at the same canonical pages, and stale URLs should be retired through redirects rather than left as dead ends.',
      'The HTML resume should be the durable source of truth because it can carry visible text, internal links, schema, and a current update path. A downloadable PDF can still be useful, but it should not become the canonical identity page unless there is a reason for that tradeoff.',
      'Structured data should be conservative. Schema.org defines sameAs as a URL that unambiguously identifies the same item, not a bucket for every social link ever created. A dead, private, or weakly matching profile should stay out of sameAs even if it once existed.',
      'ProfilePage markup works best when the visible page is clearly about one person or one organization. Google guidance describes mainEntity as the person or organization the profile page is about. That makes /about, /resume, and /ai-information useful profile surfaces if they share the same Person identifier, current description, and source links.',
      'The reconciliation process is practical: pick the canonical domain, redirect duplicate hosts, redirect stale PDFs, keep /about and /resume aligned, publish a compact source-role page, and push the same current identity to external bios. The output is not a bigger personal brand. It is a smaller, cleaner set of records that makes the current public identity easier to verify.',
    ],
  },
];

export function getResearchArticleBySlug(slug: string) {
  return RESEARCH_ARTICLES.find((article) => article.slug === slug);
}
